# cloudbuild.yaml
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run compose up docker-compose.prod.yml \
          --region us-central1 \
          --quiet
options:
  logging: CLOUD_LOGGING_ONLY