namespace MaintainArr.Api.Contracts;

public sealed record MaintenancePartsKitLineResponse(
    Guid PartsKitLineId,
    Guid PartsKitId,
    string ItemRef,
    string ItemDescriptionSnapshot,
    decimal Quantity,
    string UnitOfMeasure,
    bool Required,
    bool SubstituteAllowed,
    int SortOrder,
    string? SupplyarrPartId,
    string? PartNumberSnapshot,
    string? ManufacturerPartNumberSnapshot,
    string? VendorPartNumberSnapshot,
    string Criticality,
    bool Consumable,
    bool Serialized,
    bool CoreReturnExpected,
    bool Hazardous,
    bool WarrantySensitive,
    string? RequiredByTask,
    string? Notes,
    IReadOnlyList<string> Tags,
    IReadOnlyList<string> PreferredSubstituteRefs,
    bool IsPlaceholder,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record MaintenancePartsKitResponse(
    Guid PartsKitId,
    string KitNumber,
    string Title,
    string Description,
    string? KitCategoryKey,
    string? KitTypeKey,
    string? PriorityKey,
    string? OwningSiteRef,
    string? OwningTeamRef,
    string? OwnerPersonId,
    string? OwnerRoleKey,
    IReadOnlyList<string> Tags,
    IReadOnlyList<string> AssetTypeApplicability,
    IReadOnlyList<string> WorkOrderTypeApplicability,
    string? PmPlanRef,
    MaintenancePartsKitDefinitionResponse? Definition,
    string Status,
    int Version,
    IReadOnlyList<Guid> LineRefs,
    IReadOnlyList<MaintenancePartsKitLineResponse> Lines,
    DateTimeOffset? EffectiveAt,
    DateTimeOffset? ExpiresAt,
    DateTimeOffset? ActivatedAt,
    DateTimeOffset? ApprovedAt,
    DateTimeOffset? RetiredAt,
    string? CloneSourcePartsKitId,
    string? CreatedByPersonId,
    string? UpdatedByPersonId,
    string? ActivatedByPersonId,
    string? ApprovedByPersonId,
    string? RetiredByPersonId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record MaintenancePartsKitListResponse(
    IReadOnlyList<MaintenancePartsKitResponse> Items);

public sealed record CreateMaintenancePartsKitRequest(
    string KitNumber,
    string Title,
    string? Description,
    IReadOnlyList<string>? AssetTypeApplicability,
    IReadOnlyList<string>? WorkOrderTypeApplicability,
    string? PmPlanRef,
    string? KitCategoryKey,
    string? KitTypeKey,
    string? PriorityKey,
    string? OwningSiteRef,
    string? OwningTeamRef,
    string? OwnerPersonId,
    string? OwnerRoleKey,
    IReadOnlyList<string>? Tags,
    MaintenancePartsKitDefinitionRequest? Definition,
    DateTimeOffset? EffectiveAt,
    DateTimeOffset? ExpiresAt,
    string? CloneSourcePartsKitId);

public sealed record UpdateMaintenancePartsKitRequest(
    string Title,
    string? Description,
    IReadOnlyList<string>? AssetTypeApplicability,
    IReadOnlyList<string>? WorkOrderTypeApplicability,
    string? PmPlanRef,
    string? KitCategoryKey,
    string? KitTypeKey,
    string? PriorityKey,
    string? OwningSiteRef,
    string? OwningTeamRef,
    string? OwnerPersonId,
    string? OwnerRoleKey,
    IReadOnlyList<string>? Tags,
    MaintenancePartsKitDefinitionRequest? Definition,
    DateTimeOffset? EffectiveAt,
    DateTimeOffset? ExpiresAt);

public sealed record MaintenancePartsKitPreviewRequest(
    string KitNumber,
    string Title,
    string? Description,
    IReadOnlyList<string>? AssetTypeApplicability,
    IReadOnlyList<string>? WorkOrderTypeApplicability,
    string? PmPlanRef,
    string? KitCategoryKey,
    string? KitTypeKey,
    string? PriorityKey,
    string? OwningSiteRef,
    string? OwningTeamRef,
    string? OwnerPersonId,
    string? OwnerRoleKey,
    IReadOnlyList<string>? Tags,
    MaintenancePartsKitDefinitionRequest? Definition,
    DateTimeOffset? EffectiveAt,
    DateTimeOffset? ExpiresAt,
    string? CloneSourcePartsKitId,
    string? SelectedAssetId);

public sealed record UpdateMaintenancePartsKitStatusRequest(string Status);

public sealed record CreateMaintenancePartsKitLineRequest(
    string ItemRef,
    string ItemDescriptionSnapshot,
    decimal Quantity,
    string UnitOfMeasure,
    bool Required,
    bool SubstituteAllowed);

public sealed record UpdateMaintenancePartsKitLineRequest(
    string ItemDescriptionSnapshot,
    decimal Quantity,
    string UnitOfMeasure,
    bool Required,
    bool SubstituteAllowed);

public sealed record MaintenancePartsKitDefinitionRequest(
    IReadOnlyList<string>? ApplicabilityWorkOrderTypes,
    IReadOnlyList<string>? ApplicabilityPmProgramRefs,
    IReadOnlyList<string>? ApplicabilityInspectionTemplateRefs,
    IReadOnlyList<string>? ApplicabilityDefectTypes,
    IReadOnlyList<string>? ApplicabilityTaskTemplateRefs,
    IReadOnlyList<string>? ApplicabilityRepairCategories,
    IReadOnlyList<string>? WorkSourceCompatibilities,
    MaintenancePartsKitAssetScopeRequest? AssetScope,
    IReadOnlyList<MaintenancePartsKitItemRequest>? Items,
    IReadOnlyList<MaintenancePartsKitQuantityRuleRequest>? QuantityRules,
    MaintenancePartsKitAvailabilityRequest? Availability,
    MaintenancePartsKitWorkOrderBehaviorRequest? WorkOrderBehavior,
    MaintenancePartsKitComplianceRequest? Compliance,
    MaintenancePartsKitApprovalRequest? Approval,
    string? ChangeReason,
    string? VersionLabel);

public sealed record MaintenancePartsKitDefinitionResponse(
    IReadOnlyList<string> ApplicabilityWorkOrderTypes,
    IReadOnlyList<string> ApplicabilityPmProgramRefs,
    IReadOnlyList<string> ApplicabilityInspectionTemplateRefs,
    IReadOnlyList<string> ApplicabilityDefectTypes,
    IReadOnlyList<string> ApplicabilityTaskTemplateRefs,
    IReadOnlyList<string> ApplicabilityRepairCategories,
    IReadOnlyList<string> WorkSourceCompatibilities,
    MaintenancePartsKitAssetScopeResponse AssetScope,
    IReadOnlyList<MaintenancePartsKitItemResponse> Items,
    IReadOnlyList<MaintenancePartsKitQuantityRuleResponse> QuantityRules,
    MaintenancePartsKitAvailabilityResponse Availability,
    MaintenancePartsKitWorkOrderBehaviorResponse WorkOrderBehavior,
    MaintenancePartsKitComplianceResponse Compliance,
    MaintenancePartsKitApprovalResponse Approval,
    string? ChangeReason,
    string? VersionLabel);

public sealed record MaintenancePartsKitAssetScopeRequest(
    IReadOnlyList<string>? AssetClassKeys,
    IReadOnlyList<string>? AssetTypeKeys,
    IReadOnlyList<string>? AssetCategoryKeys,
    IReadOnlyList<string>? AssetStatusKeys,
    IReadOnlyList<string>? SiteRefs,
    IReadOnlyList<string>? DepartmentRefs,
    IReadOnlyList<string>? MakeKeys,
    IReadOnlyList<string>? ModelKeys,
    string? YearFrom,
    string? YearTo,
    IReadOnlyList<string>? FuelTypeKeys,
    IReadOnlyList<string>? BodyTypeKeys,
    IReadOnlyList<string>? ConfigurationKeys,
    IReadOnlyList<string>? VariantFlags,
    IReadOnlyList<string>? RequiredAttributes,
    IReadOnlyList<string>? ExcludedAttributes,
    IReadOnlyList<string>? IncludedAssetIds,
    IReadOnlyList<string>? ExcludedAssetIds);

public sealed record MaintenancePartsKitAssetScopeResponse(
    IReadOnlyList<string> AssetClassKeys,
    IReadOnlyList<string> AssetTypeKeys,
    IReadOnlyList<string> AssetCategoryKeys,
    IReadOnlyList<string> AssetStatusKeys,
    IReadOnlyList<string> SiteRefs,
    IReadOnlyList<string> DepartmentRefs,
    IReadOnlyList<string> MakeKeys,
    IReadOnlyList<string> ModelKeys,
    string? YearFrom,
    string? YearTo,
    IReadOnlyList<string> FuelTypeKeys,
    IReadOnlyList<string> BodyTypeKeys,
    IReadOnlyList<string> ConfigurationKeys,
    IReadOnlyList<string> VariantFlags,
    IReadOnlyList<string> RequiredAttributes,
    IReadOnlyList<string> ExcludedAttributes,
    IReadOnlyList<string> IncludedAssetIds,
    IReadOnlyList<string> ExcludedAssetIds);

public sealed record MaintenancePartsKitItemRequest(
    string ItemRef,
    string? SupplyarrPartId,
    string ItemDescriptionSnapshot,
    string? PartNumberSnapshot,
    string? ManufacturerPartNumberSnapshot,
    string? VendorPartNumberSnapshot,
    decimal Quantity,
    string UnitOfMeasure,
    bool Required,
    string Criticality,
    bool SubstituteAllowed,
    IReadOnlyList<string>? PreferredSubstituteRefs,
    bool Consumable,
    bool Serialized,
    bool CoreReturnExpected,
    bool Hazardous,
    bool WarrantySensitive,
    string? RequiredByTask,
    string? Notes,
    IReadOnlyList<string>? Tags,
    bool IsPlaceholder);

public sealed record MaintenancePartsKitItemResponse(
    string ItemRef,
    string? SupplyarrPartId,
    string ItemDescriptionSnapshot,
    string? PartNumberSnapshot,
    string? ManufacturerPartNumberSnapshot,
    string? VendorPartNumberSnapshot,
    decimal Quantity,
    string UnitOfMeasure,
    bool Required,
    string Criticality,
    bool SubstituteAllowed,
    IReadOnlyList<string> PreferredSubstituteRefs,
    bool Consumable,
    bool Serialized,
    bool CoreReturnExpected,
    bool Hazardous,
    bool WarrantySensitive,
    string? RequiredByTask,
    string? Notes,
    IReadOnlyList<string> Tags,
    bool IsPlaceholder);

public sealed record MaintenancePartsKitQuantityRuleRequest(
    string RuleId,
    string RuleType,
    string AppliesToItemRef,
    string? AssetConditionSummary,
    string? WorkConditionSummary,
    string? ConditionSummary,
    decimal BaseQuantity,
    decimal Multiplier,
    decimal? MinimumQuantity,
    decimal? MaximumQuantity,
    string RoundingBehavior,
    string PlainLanguageSummary);

public sealed record MaintenancePartsKitQuantityRuleResponse(
    string RuleId,
    string RuleType,
    string AppliesToItemRef,
    string? AssetConditionSummary,
    string? WorkConditionSummary,
    string? ConditionSummary,
    decimal BaseQuantity,
    decimal Multiplier,
    decimal? MinimumQuantity,
    decimal? MaximumQuantity,
    string RoundingBehavior,
    string PlainLanguageSummary);

public sealed record MaintenancePartsKitAvailabilityRequest(
    bool Enabled,
    string? PreferredFulfillmentSource,
    bool ShowSiteAvailability,
    bool ShowNearbyAvailability,
    bool ShowOnOrder,
    bool ShowEstimatedLeadTime,
    bool RequestReservation,
    string? Notes);

public sealed record MaintenancePartsKitAvailabilityResponse(
    bool Enabled,
    string? PreferredFulfillmentSource,
    bool ShowSiteAvailability,
    bool ShowNearbyAvailability,
    bool ShowOnOrder,
    bool ShowEstimatedLeadTime,
    bool RequestReservation,
    string? Notes);

public sealed record MaintenancePartsKitWorkOrderBehaviorRequest(
    bool CanBeManuallyAdded,
    bool AutoSuggestOnMatchingWorkOrder,
    bool AutoAddToMatchingWorkOrder,
    bool AutoAddToPmGeneratedWorkOrder,
    bool AutoAddAfterFailedInspectionQuestion,
    bool AutoAddAfterMatchingDefectType,
    bool RequireSupervisorApprovalBeforeAdding,
    bool RequirePartsReviewBeforeWorkCanStart,
    bool RequireAvailabilityCheckBeforeScheduling,
    bool AllowTechnicianAdjustQuantities,
    bool RequireAdjustmentReason,
    bool AllowTechnicianRemoveOptionalItems,
    bool AllowTechnicianRemoveRequiredItems,
    bool RequireReasonToRemoveRequiredItem,
    bool SnapshotKitItemsOntoWorkOrder,
    bool KeepLiveReferenceAfterWorkOrderCreation);

public sealed record MaintenancePartsKitWorkOrderBehaviorResponse(
    bool CanBeManuallyAdded,
    bool AutoSuggestOnMatchingWorkOrder,
    bool AutoAddToMatchingWorkOrder,
    bool AutoAddToPmGeneratedWorkOrder,
    bool AutoAddAfterFailedInspectionQuestion,
    bool AutoAddAfterMatchingDefectType,
    bool RequireSupervisorApprovalBeforeAdding,
    bool RequirePartsReviewBeforeWorkCanStart,
    bool RequireAvailabilityCheckBeforeScheduling,
    bool AllowTechnicianAdjustQuantities,
    bool RequireAdjustmentReason,
    bool AllowTechnicianRemoveOptionalItems,
    bool AllowTechnicianRemoveRequiredItems,
    bool RequireReasonToRemoveRequiredItem,
    bool SnapshotKitItemsOntoWorkOrder,
    bool KeepLiveReferenceAfterWorkOrderCreation);

public sealed record MaintenancePartsKitComplianceRequest(
    bool ComplianceRelated,
    IReadOnlyList<string>? GoverningBodyKeys,
    IReadOnlyList<string>? CitationRefs,
    bool SafetyCritical,
    bool ReadinessSensitive,
    bool MissingRequiredPartsBlockWorkStart,
    bool MissingRequiredPartsBlockWorkCompletion,
    bool RequireSupervisorApprovalForSubstitution,
    bool RequireDocumentationForSubstitution,
    bool RequireFinalInspectionAfterUse,
    string? LinkedInspectionTemplateId);

public sealed record MaintenancePartsKitComplianceResponse(
    bool ComplianceRelated,
    IReadOnlyList<string> GoverningBodyKeys,
    IReadOnlyList<string> CitationRefs,
    bool SafetyCritical,
    bool ReadinessSensitive,
    bool MissingRequiredPartsBlockWorkStart,
    bool MissingRequiredPartsBlockWorkCompletion,
    bool RequireSupervisorApprovalForSubstitution,
    bool RequireDocumentationForSubstitution,
    bool RequireFinalInspectionAfterUse,
    string? LinkedInspectionTemplateId);

public sealed record MaintenancePartsKitApprovalRequest(
    bool RequiresApprovalBeforeActivation,
    string? ApproverRoleKey,
    string? ApproverPersonId,
    bool RetireReplacedKitAfterActivation,
    string? NotesForApprover);

public sealed record MaintenancePartsKitApprovalResponse(
    bool RequiresApprovalBeforeActivation,
    string? ApproverRoleKey,
    string? ApproverPersonId,
    bool RetireReplacedKitAfterActivation,
    string? NotesForApprover);

public sealed record MaintenancePartsKitValidationResponse(
    bool IsValid,
    IReadOnlyList<string> Errors,
    IReadOnlyList<string> Warnings,
    int CompatibleAssetCount,
    int SampleAssetCount,
    int RequiredItemCount,
    int OptionalItemCount,
    int CriticalItemCount,
    string Summary,
    bool CanDraftSave,
    bool CanActivate,
    bool CanApprove);

public sealed record MaintenancePartsKitPreviewItemResponse(
    string ItemRef,
    string ItemDescriptionSnapshot,
    decimal BaseQuantity,
    decimal CalculatedQuantity,
    string UnitOfMeasure,
    string Criticality,
    string AvailabilityStatus,
    string AvailabilityMessage,
    string? SupplyarrPartId,
    string? PartNumberSnapshot,
    bool Required,
    bool SubstituteAllowed,
    bool IsPlaceholder);

public sealed record MaintenancePartsKitPreviewResponse(
    MaintenancePartsKitValidationResponse Validation,
    IReadOnlyList<AssetSearchResponse> SampleAssets,
    IReadOnlyList<MaintenancePartsKitPreviewItemResponse> Items,
    IReadOnlyList<string> Warnings,
    IReadOnlyList<string> Blockers,
    string AssetScopeSummary,
    string WorkOrderBehaviorSummary,
    string ComplianceSummary,
    string ApprovalSummary,
    string AvailabilitySummary);
