namespace MaintainArr.Api.Contracts;

public sealed record RecallProviderSummaryResponse(
    string ProviderKey,
    string DisplayName,
    string Description,
    string SourceOfTruth,
    string Status,
    bool SupportsVehicleSearch,
    bool SupportsCampaignSearch,
    bool SupportsManualCampaigns,
    DateTimeOffset? LastCheckedAt,
    DateTimeOffset? LastSuccessfulAt,
    string? LastError);

public sealed record RecallProviderHealthResponse(
    string ProviderKey,
    string Status,
    string Message,
    DateTimeOffset CheckedAt,
    int? LatencyMs);

public sealed record RecallCampaignApplicabilityResponse(
    Guid ApplicabilityId,
    Guid RecallCampaignId,
    int? ModelYear,
    string? Make,
    string? Model,
    string? AssetClass,
    string? AssetType,
    string? BodyClass,
    string? VehicleType,
    string? FuelType,
    string? EngineFamily,
    string? EngineManufacturer,
    string? ComponentCategory,
    string? TireBrand,
    string? TireLine,
    string? TireSize,
    string? EquipmentMake,
    string? EquipmentModel,
    string? SerialRangeStart,
    string? SerialRangeEnd,
    DateTimeOffset? ProductionStartDate,
    DateTimeOffset? ProductionEndDate,
    string? Notes,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record RecallCampaignResponse(
    Guid CampaignId,
    string SourceProvider,
    string SourceType,
    string? SourceProviderRecordId,
    string? NhtsaCampaignNumber,
    string? NhtsaActionNumber,
    string? ManufacturerCampaignNumber,
    string? CampaignTitle,
    string Manufacturer,
    string Component,
    string? ReportReceivedDate,
    string? CampaignStartDate,
    string? CampaignEndDate,
    string CampaignStatus,
    int? PotentialUnitsAffected,
    string Summary,
    string Consequence,
    string Remedy,
    string Notes,
    bool ParkIt,
    bool ParkOutside,
    bool OverTheAirUpdate,
    string RecallType,
    string? SourceUrl,
    DateTimeOffset? FetchedAt,
    IReadOnlyList<RecallCampaignApplicabilityResponse> Applicability,
    int AssetCaseCount,
    int OpenCaseCount,
    int VerifiedOpenCaseCount,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record AssetRecallCaseResponse(
    Guid CaseId,
    Guid AssetId,
    Guid RecallCampaignId,
    string CampaignNumber,
    string? CampaignTitle,
    string Manufacturer,
    string Component,
    string Summary,
    string Consequence,
    string Remedy,
    string Notes,
    string? ModelYear,
    string? Make,
    string? Model,
    string? ReportReceivedDate,
    string SourceProvider,
    string SourceType,
    string? SourceUrl,
    DateTimeOffset? FetchedAt,
    string MatchBasis,
    string MatchConfidence,
    decimal? MatchScore,
    string Status,
    string ReadinessImpact,
    string Reason,
    string VerificationStatus,
    string? VerificationSource,
    string? VerificationMethod,
    string? VerifiedByPersonId,
    DateTimeOffset? VerifiedAt,
    string? DismissedByPersonId,
    DateTimeOffset? DismissedAt,
    string? DismissalReason,
    bool ParkIt,
    bool ParkOutside,
    bool OverTheAirUpdate,
    Guid? EvidenceDocumentId,
    string? EvidenceUrl,
    string? EvidenceText,
    Guid? WorkOrderId,
    Guid? InspectionRunId,
    Guid? DefectId,
    Guid? ReadinessHoldId,
    string ActionType,
    string ActionStatus,
    DateTimeOffset DetectedAt,
    DateTimeOffset? LastRefreshedAt,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record RecallDashboardItemResponse(
    Guid CaseId,
    Guid AssetId,
    string AssetTag,
    string AssetName,
    string CampaignNumber,
    string Component,
    string MatchBasis,
    string MatchConfidence,
    string Status,
    string ReadinessImpact,
    string SourceProvider,
    DateTimeOffset DetectedAt,
    DateTimeOffset? LastRefreshedAt,
    DateTimeOffset? NextReviewAt,
    Guid? WorkOrderId,
    string? SiteRef);

public sealed record RecallDashboardResponse(
    DateTimeOffset GeneratedAt,
    int VerifiedOpenRecallCount,
    int PotentialMatchCount,
    int ParkItWarningCount,
    int ParkOutsideWarningCount,
    int WorkOrdersCreatedCount,
    int CompletedVerifiedThisMonthCount,
    int OverdueReviewCount,
    int AssetsNeverCheckedCount,
    IReadOnlyList<RecallDashboardItemResponse> AttentionItems);

public sealed record RecallVehicleSearchRequest(
    int Year,
    string Make,
    string Model);

public sealed record RecallCampaignSearchRequest(
    string CampaignNumber);

public sealed record RecallCampaignApplicabilityRequest(
    int? ModelYear = null,
    string? Make = null,
    string? Model = null,
    string? AssetClass = null,
    string? AssetType = null,
    string? BodyClass = null,
    string? VehicleType = null,
    string? FuelType = null,
    string? EngineFamily = null,
    string? EngineManufacturer = null,
    string? ComponentCategory = null,
    string? TireBrand = null,
    string? TireLine = null,
    string? TireSize = null,
    string? EquipmentMake = null,
    string? EquipmentModel = null,
    string? SerialRangeStart = null,
    string? SerialRangeEnd = null,
    DateTimeOffset? ProductionStartDate = null,
    DateTimeOffset? ProductionEndDate = null,
    string? Notes = null);

public sealed record CreateRecallCampaignRequest(
    string SourceProvider,
    string SourceType,
    string? SourceProviderRecordId,
    string? NhtsaCampaignNumber,
    string? NhtsaActionNumber,
    string? ManufacturerCampaignNumber,
    string? CampaignTitle,
    string Manufacturer,
    string Component,
    string? ReportReceivedDate,
    string? CampaignStartDate,
    string? CampaignEndDate,
    string CampaignStatus,
    int? PotentialUnitsAffected,
    string Summary,
    string Consequence,
    string Remedy,
    string Notes,
    bool ParkIt,
    bool ParkOutside,
    bool OverTheAirUpdate,
    string RecallType,
    string? SourceUrl,
    string? SourceRawJson,
    IReadOnlyList<RecallCampaignApplicabilityRequest>? Applicability,
    IReadOnlyList<Guid>? AffectedAssetIds,
    bool CreateCandidatesNow = false,
    bool CreateWorkOrdersNow = false);

public sealed record UpdateRecallCampaignRequest(
    string? CampaignTitle = null,
    string? Manufacturer = null,
    string? Component = null,
    string? ReportReceivedDate = null,
    string? CampaignStartDate = null,
    string? CampaignEndDate = null,
    string? CampaignStatus = null,
    int? PotentialUnitsAffected = null,
    string? Summary = null,
    string? Consequence = null,
    string? Remedy = null,
    string? Notes = null,
    bool? ParkIt = null,
    bool? ParkOutside = null,
    bool? OverTheAirUpdate = null,
    string? RecallType = null,
    string? SourceUrl = null,
    string? SourceRawJson = null,
    IReadOnlyList<RecallCampaignApplicabilityRequest>? Applicability = null);

public sealed record VerifyAssetRecallRequest(
    string VerificationSource,
    string VerificationMethod,
    string VerificationStatus,
    string? VerifiedByPersonId,
    DateTimeOffset? VerifiedAt,
    Guid? EvidenceDocumentId,
    string? EvidenceUrl,
    string? EvidenceText,
    string? ProviderRawJson,
    DateTimeOffset? ExpiresAt,
    DateTimeOffset? NextReviewAt,
    string? Notes);

public sealed record DismissAssetRecallRequest(
    string DismissalReason,
    string? DismissedByPersonId = null);

public sealed record CreateRecallWorkItemRequest(
    string ActionType,
    string? ActionStatus = null,
    string? RequiredAction = null);

public sealed record ReleaseRecallHoldRequest(
    string? ReleasedByPersonId,
    string? ReleaseReason);
