namespace AssurArr.Api.Contracts;

public sealed record AssurArrDashboardCardResponse(
    string Key,
    string Title,
    string Description,
    int Count,
    string Tone);

public sealed record AssurArrTimelineEventResponse(
    Guid Id,
    string SubjectType,
    Guid SubjectId,
    string EventType,
    string? Details,
    DateTimeOffset OccurredAt);

public sealed record AssurArrDashboardResponse(
    DateTimeOffset GeneratedAt,
    IReadOnlyList<AssurArrDashboardCardResponse> Cards,
    IReadOnlyList<AssurArrTimelineEventResponse> RecentEvents);

public sealed record AssurArrListItemResponse(
    Guid Id,
    string Number,
    string Title,
    string Status,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record AssurArrNonconformanceResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string NonconformanceType,
    string Category,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string? CustomerImpact,
    string? SupplierImpact,
    string? SafetyImpact,
    string? ComplianceImpact,
    bool RecurrenceFlag,
    string? RepeatOfNonconformanceRef,
    DateTimeOffset? DueAt);

public sealed record CreateAssurArrNonconformanceRequest(
    string Title,
    string Description,
    string Severity,
    string NonconformanceType,
    string Category,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string? CustomerImpact,
    string? SupplierImpact,
    string? SafetyImpact,
    string? ComplianceImpact,
    bool RecurrenceFlag,
    string? RepeatOfNonconformanceRef,
    DateTimeOffset? DueAt);

public sealed record AssurArrQualityHoldResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string HoldType,
    string HoldScope,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string? HoldReason,
    string? ReleaseReason,
    string? RejectionReason,
    string? ConditionalReleaseTerms,
    decimal? QuantityHeld,
    string? UnitOfMeasure,
    string? LotNumber,
    string? SerialNumber,
    DateTimeOffset? PlacedAt,
    Guid? PlacedByPersonId,
    DateTimeOffset? ReleasedAt,
    Guid? ReleasedByPersonId,
    DateTimeOffset? ExpiresAt);

public sealed record CreateAssurArrQualityHoldRequest(
    string Title,
    string Description,
    string Severity,
    string HoldType,
    string HoldScope,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string? HoldReason,
    decimal? QuantityHeld,
    string? UnitOfMeasure,
    string? LotNumber,
    string? SerialNumber,
    DateTimeOffset? ExpiresAt);

public sealed record AssurArrCapaResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string CapaType,
    string SourceType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    Guid? SponsorPersonId,
    string? RootCauseSummary,
    DateTimeOffset? DueAt,
    IReadOnlyList<string> RelatedNonconformanceRefs,
    IReadOnlyList<string> RelatedAuditFindingRefs);

public sealed record CreateAssurArrCapaRequest(
    string Title,
    string Description,
    string Severity,
    string CapaType,
    string SourceType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    Guid? SponsorPersonId,
    string? RootCauseSummary,
    DateTimeOffset? DueAt,
    string[] RelatedNonconformanceRefs,
    string[] RelatedAuditFindingRefs);

public sealed record AssurArrQualityAuditResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string AuditType,
    string? AuditScope,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    IReadOnlyList<string> AuditorPersonIds,
    Guid? LeadAuditorPersonId,
    Guid? StaffArrSiteId,
    Guid? StaffArrLocationId,
    string? SupplierRef,
    string? CustomerRef,
    DateTimeOffset? PlannedStartAt,
    DateTimeOffset? PlannedEndAt,
    DateTimeOffset? ActualStartAt,
    DateTimeOffset? ActualEndAt,
    IReadOnlyList<string> ChecklistRefs,
    IReadOnlyList<string> FindingRefs);

public sealed record CreateAssurArrQualityAuditRequest(
    string Title,
    string Description,
    string Severity,
    string AuditType,
    string? AuditScope,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string[] AuditorPersonIds,
    Guid? LeadAuditorPersonId,
    Guid? StaffArrSiteId,
    Guid? StaffArrLocationId,
    string? SupplierRef,
    string? CustomerRef,
    DateTimeOffset? PlannedStartAt,
    DateTimeOffset? PlannedEndAt,
    string[] ChecklistRefs);

public sealed record AssurArrAuditFindingResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string FindingType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string? AuditRef,
    string? NonconformanceRef,
    string? CapaRef,
    DateTimeOffset? DueAt);

public sealed record CreateAssurArrAuditFindingRequest(
    string Title,
    string Description,
    string Severity,
    string FindingType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string? AuditRef,
    string? NonconformanceRef,
    string? CapaRef,
    DateTimeOffset? DueAt);

public sealed record AssurArrQualityStatusSnapshotResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string TargetProduct,
    string TargetObjectRef,
    string QualityStatus,
    IReadOnlyList<string> ActiveHoldRefs,
    IReadOnlyList<string> OpenNonconformanceRefs,
    IReadOnlyList<string> OpenCapaRefs,
    IReadOnlyList<string> OpenFindingRefs,
    DateTimeOffset? LastReviewedAt,
    Guid? ReviewedByPersonId,
    DateTimeOffset? ExpiresAt);

public sealed record CreateAssurArrQualityStatusSnapshotRequest(
    string TargetProduct,
    string TargetObjectRef,
    string QualityStatus,
    string Severity,
    string Title,
    string Description,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string[] ActiveHoldRefs,
    string[] OpenNonconformanceRefs,
    string[] OpenCapaRefs,
    string[] OpenFindingRefs,
    DateTimeOffset? ExpiresAt);

public sealed record AssurArrQualityScorecardResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string TargetType,
    string TargetRef,
    DateTimeOffset PeriodStart,
    DateTimeOffset PeriodEnd,
    decimal? OverallScore,
    string QualityStatus,
    string Trend,
    DateTimeOffset GeneratedAt,
    string GeneratedBy,
    Guid? ReviewedByPersonId,
    DateTimeOffset? ReviewedAt,
    IReadOnlyList<string> MetricRefs);

public sealed record AssurArrQualityReviewResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string ReviewType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string? SourceReviewRef,
    Guid? ReviewerPersonId,
    DateTimeOffset? RequestedAt,
    DateTimeOffset? DueAt,
    DateTimeOffset? DecisionAt,
    string? DecisionReason,
    IReadOnlyList<string> RequiredEvidenceRefs,
    IReadOnlyList<string> SubmittedEvidenceRefs,
    string? Notes);

public sealed record CreateAssurArrQualityReviewRequest(
    string Title,
    string Description,
    string Severity,
    string ReviewType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string? SourceReviewRef,
    Guid? ReviewerPersonId,
    DateTimeOffset? RequestedAt,
    DateTimeOffset? DueAt,
    string? DecisionReason,
    string[] RequiredEvidenceRefs,
    string[] SubmittedEvidenceRefs,
    string? Notes);

public sealed record AssurArrQualityReleaseResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string HoldRef,
    string ReleaseType,
    Guid? RequestedByPersonId,
    DateTimeOffset? RequestedAt,
    Guid? ApprovedByPersonId,
    DateTimeOffset? ApprovedAt,
    DateTimeOffset? ExecutedAt,
    string? Conditions,
    DateTimeOffset? ExpirationAt,
    IReadOnlyList<string> EvidenceRecordRefs,
    string? Notes);

public sealed record CreateAssurArrQualityReleaseRequest(
    string Title,
    string Description,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string HoldRef,
    string ReleaseType,
    Guid? RequestedByPersonId,
    DateTimeOffset? RequestedAt,
    string? Conditions,
    DateTimeOffset? ExpirationAt,
    string[] EvidenceRecordRefs,
    string? Notes);

public sealed record CreateAssurArrQualityScorecardRequest(
    string TargetType,
    string TargetRef,
    DateTimeOffset PeriodStart,
    DateTimeOffset PeriodEnd,
    decimal? OverallScore,
    string QualityStatus,
    string Trend,
    string Title,
    string Description,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string[] MetricRefs);

public sealed record UpdateAssurArrStatusRequest(string Status, string? ClosureSummary = null);
