namespace AssurArr.Api.Contracts;

public sealed record AssurArrDashboardCardResponse(
    string Key,
    string Title,
    string Description,
    int Count,
    string Tone);

public sealed record AssurArrTimelineEventResponse(
    Guid Id,
    string SubjectType,
    Guid SubjectId,
    string EventType,
    string? Details,
    DateTimeOffset OccurredAt);

public sealed record AssurArrDashboardResponse(
    DateTimeOffset GeneratedAt,
    IReadOnlyList<AssurArrDashboardCardResponse> Cards,
    IReadOnlyList<AssurArrTimelineEventResponse> RecentEvents);

public sealed record AssurArrListItemResponse(
    Guid Id,
    string Number,
    string Title,
    string Status,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record AssurArrNonconformanceResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string NonconformanceType,
    string Category,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string? CustomerImpact,
    string? SupplierImpact,
    string? SafetyImpact,
    string? ComplianceImpact,
    bool RecurrenceFlag,
    string? RepeatOfNonconformanceRef,
    string? RootCauseRef,
    string[] BlockerRefs,
    DateTimeOffset? DueAt);

public sealed record CreateAssurArrNonconformanceRequest(
    string Title,
    string Description,
    string Severity,
    string NonconformanceType,
    string Category,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string? CustomerImpact,
    string? SupplierImpact,
    string? SafetyImpact,
    string? ComplianceImpact,
    bool RecurrenceFlag,
    string? RepeatOfNonconformanceRef,
    string? RootCauseRef,
    string[] BlockerRefs,
    DateTimeOffset? DueAt);

public sealed record AssurArrQualityHoldResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string HoldType,
    string HoldScope,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string? HoldReason,
    string? ReleaseReason,
    string? RejectionReason,
    string? ConditionalReleaseTerms,
    IReadOnlyList<string> ReleaseRequirements,
    IReadOnlyList<string> ReleaseApprovalRefs,
    decimal? QuantityHeld,
    string? UnitOfMeasure,
    string? LotNumber,
    string? SerialNumber,
    DateTimeOffset? PlacedAt,
    Guid? PlacedByPersonId,
    DateTimeOffset? ReleasedAt,
    Guid? ReleasedByPersonId,
    DateTimeOffset? RejectedAt,
    Guid? RejectedByPersonId,
    DateTimeOffset? ExpiresAt);

public sealed record CreateAssurArrQualityHoldRequest(
    string Title,
    string Description,
    string Severity,
    string HoldType,
    string HoldScope,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string? HoldReason,
    decimal? QuantityHeld,
    string? UnitOfMeasure,
    string? LotNumber,
    string? SerialNumber,
    DateTimeOffset? ExpiresAt);

public sealed record AssurArrCapaResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string CapaType,
    string SourceType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    Guid? SponsorPersonId,
    string? RootCauseSummary,
    DateTimeOffset? DueAt,
    IReadOnlyList<string> RelatedNonconformanceRefs,
    IReadOnlyList<string> RelatedAuditFindingRefs,
    IReadOnlyList<string> EffectivenessVerificationRefs);

public sealed record CreateAssurArrCapaRequest(
    string Title,
    string Description,
    string Severity,
    string CapaType,
    string SourceType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    Guid? SponsorPersonId,
    string? RootCauseSummary,
    DateTimeOffset? DueAt,
    string[] RelatedNonconformanceRefs,
    string[] RelatedAuditFindingRefs,
    string[] EffectivenessVerificationRefs);

public sealed record AssurArrCapaActionResponse(
    Guid Id,
    string Number,
    Guid CapaId,
    string Title,
    string Description,
    string Status,
    string ActionType,
    Guid? AssignedPersonId,
    string? AssignedTeamRef,
    string? SourceProductActionRef,
    string TargetProduct,
    string? TargetObjectRef,
    DateTimeOffset? DueAt,
    DateTimeOffset? StartedAt,
    DateTimeOffset? CompletedAt,
    Guid? CompletedByPersonId,
    bool VerificationRequired,
    DateTimeOffset? VerifiedAt,
    Guid? VerifiedByPersonId,
    IReadOnlyList<string> EvidenceRecordRefs,
    IReadOnlyList<string> BlockerRefs,
    string? Notes,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record AssurArrCapaActionBlockerResponse(
    Guid Id,
    string Number,
    Guid CapaActionId,
    string BlockerType,
    string? SourceProduct,
    string? SourceObjectRef,
    string Title,
    string Description,
    string Status,
    DateTimeOffset CreatedAt,
    DateTimeOffset? ResolvedAt,
    Guid? ResolvedByPersonId);

public sealed record CreateAssurArrCapaActionBlockerRequest(
    string BlockerType,
    string? SourceProduct,
    string? SourceObjectRef,
    string Title,
    string Description);

public sealed record UpdateAssurArrCapaActionBlockerStatusRequest(
    string Status,
    Guid? ResolvedByPersonId,
    DateTimeOffset? ResolvedAt);

public sealed record CreateAssurArrCapaActionRequest(
    string Title,
    string Description,
    string ActionType,
    Guid? AssignedPersonId,
    string? AssignedTeamRef,
    string? SourceProductActionRef,
    string TargetProduct,
    string? TargetObjectRef,
    DateTimeOffset? DueAt,
    bool VerificationRequired,
    string[] EvidenceRecordRefs,
    string[] BlockerRefs,
    string? Notes);

public sealed record UpdateAssurArrCapaActionStatusRequest(
    string Status,
    Guid? CompletedByPersonId,
    DateTimeOffset? CompletedAt,
    Guid? VerifiedByPersonId,
    DateTimeOffset? VerifiedAt,
    string? ClosureSummary);

public sealed record AssurArrVerificationPlanResponse(
    Guid Id,
    string Number,
    Guid CapaId,
    string Title,
    string Description,
    string VerificationType,
    string SuccessCriteria,
    int? SampleSize,
    int? ObservationPeriodDays,
    IReadOnlyList<string> RequiredEvidenceTypes,
    Guid? ResponsiblePersonId,
    DateTimeOffset? PlannedVerificationAt,
    string Status,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record CreateAssurArrVerificationPlanRequest(
    string Title,
    string Description,
    string VerificationType,
    string SuccessCriteria,
    int? SampleSize,
    int? ObservationPeriodDays,
    string[] RequiredEvidenceTypes,
    Guid? ResponsiblePersonId,
    DateTimeOffset? PlannedVerificationAt);

public sealed record UpdateAssurArrVerificationPlanStatusRequest(
    string Status,
    string? ClosureSummary = null);

public sealed record AssurArrEffectivenessVerificationResponse(
    Guid Id,
    string Number,
    Guid CapaId,
    Guid? VerificationPlanId,
    string Status,
    Guid? PerformedByPersonId,
    DateTimeOffset? PerformedAt,
    string? ResultSummary,
    IReadOnlyList<string> EvidenceRecordRefs,
    IReadOnlyList<string> MetricResults,
    bool RecurrenceFound,
    bool FollowUpRequired,
    string? ReopenedCapaRef,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record CreateAssurArrEffectivenessVerificationRequest(
    Guid? VerificationPlanId,
    string Status,
    Guid? PerformedByPersonId,
    DateTimeOffset? PerformedAt,
    string? ResultSummary,
    string[] EvidenceRecordRefs,
    string[] MetricResults,
    bool RecurrenceFound,
    bool FollowUpRequired,
    string? ReopenedCapaRef);

public sealed record UpdateAssurArrEffectivenessVerificationStatusRequest(
    string Status,
    string? ResultSummary = null,
    bool? RecurrenceFound = null,
    bool? FollowUpRequired = null,
    string? ReopenedCapaRef = null);

public sealed record AssurArrQualityAuditResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string AuditType,
    string? AuditScope,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    IReadOnlyList<string> AuditorPersonIds,
    Guid? LeadAuditorPersonId,
    Guid? StaffArrSiteId,
    Guid? StaffArrLocationId,
    string? SupplierRef,
    string? CustomerRef,
    DateTimeOffset? PlannedStartAt,
    DateTimeOffset? PlannedEndAt,
    DateTimeOffset? ActualStartAt,
    DateTimeOffset? ActualEndAt,
    IReadOnlyList<string> ChecklistRefs,
    IReadOnlyList<string> FindingRefs);

public sealed record CreateAssurArrQualityAuditRequest(
    string Title,
    string Description,
    string Severity,
    string AuditType,
    string? AuditScope,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string[] AuditorPersonIds,
    Guid? LeadAuditorPersonId,
    Guid? StaffArrSiteId,
    Guid? StaffArrLocationId,
    string? SupplierRef,
    string? CustomerRef,
    DateTimeOffset? PlannedStartAt,
    DateTimeOffset? PlannedEndAt,
    string[] ChecklistRefs);

public sealed record AssurArrQualityAuditChecklistResponse(
    Guid Id,
    string Number,
    Guid AuditId,
    string Title,
    string Description,
    string Status,
    IReadOnlyList<string> ItemRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary);

public sealed record CreateAssurArrQualityAuditChecklistRequest(
    string Title,
    string Description,
    string Status);

public sealed record AssurArrQualityAuditChecklistItemResponse(
    Guid Id,
    string Number,
    Guid ChecklistId,
    int Sequence,
    string Prompt,
    string? HelpText,
    string? RequirementRef,
    string ResponseType,
    bool Required,
    string? ResponseValue,
    string? Result,
    bool FindingCreated,
    string? FindingRef,
    IReadOnlyList<string> EvidenceRecordRefs,
    DateTimeOffset? AnsweredAt,
    Guid? AnsweredByPersonId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record CreateAssurArrQualityAuditChecklistItemRequest(
    int Sequence,
    string Prompt,
    string? HelpText,
    string? RequirementRef,
    string ResponseType,
    bool Required,
    string? ResponseValue,
    string? Result,
    bool FindingCreated,
    string? FindingRef,
    string[] EvidenceRecordRefs,
    Guid? AnsweredByPersonId,
    DateTimeOffset? AnsweredAt);

public sealed record UpdateAssurArrQualityAuditChecklistItemResponseRequest(
    string? ResponseValue,
    string? Result,
    bool FindingCreated,
    string? FindingRef,
    string[] EvidenceRecordRefs,
    Guid? AnsweredByPersonId,
    DateTimeOffset? AnsweredAt);

public sealed record AssurArrAuditFindingResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string FindingType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string? AuditRef,
    string? NonconformanceRef,
    string? CapaRef,
    DateTimeOffset? DueAt);

public sealed record CreateAssurArrAuditFindingRequest(
    string Title,
    string Description,
    string Severity,
    string FindingType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string? AuditRef,
    string? NonconformanceRef,
    string? CapaRef,
    DateTimeOffset? DueAt);

public sealed record AssurArrRootCauseAnalysisResponse(
    Guid Id,
    string Number,
    Guid NonconformanceId,
    string Title,
    string Description,
    string Status,
    string Method,
    string PrimaryCauseCategory,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    string? RootCauseSummary,
    IReadOnlyList<string> ContributingFactors,
    Guid? AnalyzedByPersonId,
    DateTimeOffset? CompletedAt,
    IReadOnlyList<string> EvidenceRecordRefs);

public sealed record CreateAssurArrRootCauseAnalysisRequest(
    string Title,
    string Description,
    Guid NonconformanceId,
    string Status,
    string Method,
    string PrimaryCauseCategory,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string[] RecordRefs,
    string? RootCauseSummary,
    string[] ContributingFactors,
    Guid? AnalyzedByPersonId,
    DateTimeOffset? CompletedAt,
    string[] EvidenceRecordRefs);

public sealed record AssurArrQualityStatusSnapshotResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string TargetProduct,
    string TargetObjectRef,
    string QualityStatus,
    IReadOnlyList<string> ActiveHoldRefs,
    IReadOnlyList<string> OpenNonconformanceRefs,
    IReadOnlyList<string> OpenCapaRefs,
    IReadOnlyList<string> OpenFindingRefs,
    DateTimeOffset? LastReviewedAt,
    Guid? ReviewedByPersonId,
    DateTimeOffset? ExpiresAt);

public sealed record CreateAssurArrQualityStatusSnapshotRequest(
    string TargetProduct,
    string TargetObjectRef,
    string QualityStatus,
    string Severity,
    string Title,
    string Description,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string[] ActiveHoldRefs,
    string[] OpenNonconformanceRefs,
    string[] OpenCapaRefs,
    string[] OpenFindingRefs,
    DateTimeOffset? ExpiresAt);

public sealed record AssurArrQualityScorecardResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string TargetType,
    string TargetRef,
    DateTimeOffset PeriodStart,
    DateTimeOffset PeriodEnd,
    decimal? OverallScore,
    string QualityStatus,
    string Trend,
    DateTimeOffset GeneratedAt,
    string GeneratedBy,
    Guid? ReviewedByPersonId,
    DateTimeOffset? ReviewedAt,
    IReadOnlyList<string> MetricRefs);

public sealed record AssurArrQualityMetricResponse(
    Guid Id,
    Guid ScorecardId,
    string MetricKey,
    string Title,
    string Description,
    string Category,
    decimal? Value,
    decimal? Numerator,
    decimal? Denominator,
    string? Unit,
    decimal? TargetValue,
    decimal? WarningThreshold,
    decimal? CriticalThreshold,
    string Status,
    IReadOnlyList<string> SourceProductRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record CreateAssurArrQualityMetricRequest(
    string MetricKey,
    string Title,
    string Description,
    string Category,
    decimal? Value,
    decimal? Numerator,
    decimal? Denominator,
    string? Unit,
    decimal? TargetValue,
    decimal? WarningThreshold,
    decimal? CriticalThreshold,
    string Status,
    string[] SourceProductRefs);

public sealed record ReviewAssurArrQualityScorecardRequest(
    Guid? ReviewedByPersonId,
    DateTimeOffset? ReviewedAt);

public sealed record AssurArrQualityRiskProfileResponse(
    Guid Id,
    string TargetType,
    string TargetRef,
    string RiskLevel,
    IReadOnlyList<string> RiskFactors,
    int OpenIssueCount,
    int RepeatIssueCount,
    int CriticalIssueCount,
    DateTimeOffset? LastIncidentAt,
    IReadOnlyList<string> MitigationActions,
    DateTimeOffset? ReviewedAt,
    Guid? ReviewedByPersonId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record CreateAssurArrQualityRiskProfileRequest(
    string TargetType,
    string TargetRef,
    string RiskLevel,
    string[] RiskFactors,
    int OpenIssueCount,
    int RepeatIssueCount,
    int CriticalIssueCount,
    DateTimeOffset? LastIncidentAt,
    string[] MitigationActions,
    DateTimeOffset? ReviewedAt,
    Guid? ReviewedByPersonId);

public sealed record AssurArrQualityReviewResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string ReviewType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string? SourceReviewRef,
    Guid? ReviewerPersonId,
    DateTimeOffset? RequestedAt,
    DateTimeOffset? DueAt,
    DateTimeOffset? DecisionAt,
    string? DecisionReason,
    IReadOnlyList<string> RequiredEvidenceRefs,
    IReadOnlyList<string> SubmittedEvidenceRefs,
    string? Notes);

public sealed record CreateAssurArrQualityReviewRequest(
    string Title,
    string Description,
    string Severity,
    string ReviewType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string? SourceReviewRef,
    Guid? ReviewerPersonId,
    DateTimeOffset? RequestedAt,
    DateTimeOffset? DueAt,
    string? DecisionReason,
    string[] RequiredEvidenceRefs,
    string[] SubmittedEvidenceRefs,
    string? Notes);

public sealed record AssurArrQualityReleaseResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string HoldRef,
    string ReleaseType,
    Guid? RequestedByPersonId,
    DateTimeOffset? RequestedAt,
    Guid? ApprovedByPersonId,
    DateTimeOffset? ApprovedAt,
    DateTimeOffset? ExecutedAt,
    string? Conditions,
    DateTimeOffset? ExpirationAt,
    IReadOnlyList<string> EvidenceRecordRefs,
    string? Notes);

public sealed record CreateAssurArrQualityReleaseRequest(
    string Title,
    string Description,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string HoldRef,
    string ReleaseType,
    Guid? RequestedByPersonId,
    DateTimeOffset? RequestedAt,
    string? Conditions,
    DateTimeOffset? ExpirationAt,
    string[] EvidenceRecordRefs,
    string? Notes);

public sealed record AssurArrContainmentActionResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string ActionType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    string? NonconformanceRef,
    Guid? AssignedPersonId,
    string? AssignedTeamRef,
    string? SourceProductActionRef,
    DateTimeOffset? DueAt,
    DateTimeOffset? StartedAt,
    DateTimeOffset? CompletedAt,
    Guid? CompletedByPersonId,
    bool VerificationRequired,
    Guid? VerifiedByPersonId,
    DateTimeOffset? VerifiedAt,
    IReadOnlyList<string> EvidenceRecordRefs,
    string? Notes,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary);

public sealed record CreateAssurArrContainmentActionRequest(
    string Title,
    string Description,
    string Severity,
    string ActionType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    string? NonconformanceRef,
    Guid? AssignedPersonId,
    string? AssignedTeamRef,
    string? SourceProductActionRef,
    DateTimeOffset? DueAt,
    bool VerificationRequired,
    string[] EvidenceRecordRefs,
    string? Notes);

public sealed record AssurArrDispositionResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string DispositionType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    string? NonconformanceRef,
    Guid? DecisionByPersonId,
    DateTimeOffset? DecisionAt,
    Guid? ApprovedByPersonId,
    DateTimeOffset? ApprovedAt,
    string? Rationale,
    IReadOnlyList<string> RequiredActions,
    string? ExecutionProduct,
    string? ExecutionObjectRef,
    IReadOnlyList<string> EvidenceRecordRefs,
    string? Notes,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary);

public sealed record CreateAssurArrDispositionRequest(
    string Title,
    string Description,
    string Severity,
    string DispositionType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    string? NonconformanceRef,
    Guid? DecisionByPersonId,
    DateTimeOffset? DecisionAt,
    Guid? ApprovedByPersonId,
    DateTimeOffset? ApprovedAt,
    string? Rationale,
    string[] RequiredActions,
    string? ExecutionProduct,
    string? ExecutionObjectRef,
    string[] EvidenceRecordRefs,
    string? Notes);

public sealed record AssurArrSupplierQualityIssueResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string IssueType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    IReadOnlyList<string> AffectedReceiptRefs,
    IReadOnlyList<string> AffectedPurchaseOrderRefs,
    IReadOnlyList<string> AffectedItemRefs,
    string? SupplierRef,
    string? NonconformanceRef,
    string? ScarRef,
    IReadOnlyList<string> HoldRefs,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    Guid? OwnerPersonId,
    DateTimeOffset? OpenedAt);

public sealed record CreateAssurArrSupplierQualityIssueRequest(
    string Title,
    string Description,
    string Severity,
    string IssueType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedReceiptRefs,
    string[] AffectedPurchaseOrderRefs,
    string[] AffectedItemRefs,
    string? SupplierRef,
    string? NonconformanceRef,
    string? ScarRef,
    string[] HoldRefs,
    string[] RecordRefs,
    Guid? OwnerPersonId,
    DateTimeOffset? OpenedAt);

public sealed record AssurArrSupplierCorrectiveActionRequestResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    string? SupplierRef,
    string? SourceNonconformanceRef,
    string? SourceCapaRef,
    Guid? RequestedByPersonId,
    DateTimeOffset? RequestedAt,
    DateTimeOffset? SupplierDueAt,
    IReadOnlyList<string> SupplierResponseRecordRefs,
    Guid? ReviewPersonId,
    DateTimeOffset? ReviewedAt,
    string? ReviewDecision,
    string? FollowUpCapaRef,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    Guid? OwnerPersonId);

public sealed record CreateAssurArrSupplierCorrectiveActionRequest(
    string Title,
    string Description,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    string? SupplierRef,
    string? SourceNonconformanceRef,
    string? SourceCapaRef,
    Guid? RequestedByPersonId,
    DateTimeOffset? RequestedAt,
    DateTimeOffset? SupplierDueAt,
    string[] SupplierResponseRecordRefs,
    Guid? ReviewPersonId,
    DateTimeOffset? ReviewedAt,
    string? ReviewDecision,
    string? FollowUpCapaRef,
    string[] RecordRefs,
    Guid? OwnerPersonId);

public sealed record AssurArrCustomerComplaintQualityCaseResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string ComplaintType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    IReadOnlyList<string> AffectedOrderRefs,
    IReadOnlyList<string> AffectedShipmentRefs,
    IReadOnlyList<string> AffectedItemRefs,
    IReadOnlyList<string> AffectedAssetRefs,
    string? CustomerRef,
    string? CustomerContactSnapshot,
    string? CustomerLocationRef,
    string? NonconformanceRef,
    IReadOnlyList<string> HoldRefs,
    IReadOnlyList<string> CapaRefs,
    IReadOnlyList<string> CustomerResponseRecordRefs,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    Guid? OwnerPersonId,
    DateTimeOffset? ReceivedAt,
    Guid? ReceivedByPersonId,
    DateTimeOffset? CustomerResponseDueAt);

public sealed record CreateAssurArrCustomerComplaintQualityCaseRequest(
    string Title,
    string Description,
    string Severity,
    string ComplaintType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedOrderRefs,
    string[] AffectedShipmentRefs,
    string[] AffectedItemRefs,
    string[] AffectedAssetRefs,
    string? CustomerRef,
    string? CustomerContactSnapshot,
    string? CustomerLocationRef,
    string? NonconformanceRef,
    string[] HoldRefs,
    string[] CapaRefs,
    string[] CustomerResponseRecordRefs,
    string[] RecordRefs,
    Guid? OwnerPersonId,
    DateTimeOffset? ReceivedAt,
    Guid? ReceivedByPersonId,
    DateTimeOffset? CustomerResponseDueAt);

public sealed record CreateAssurArrQualityScorecardRequest(
    string TargetType,
    string TargetRef,
    DateTimeOffset PeriodStart,
    DateTimeOffset PeriodEnd,
    decimal? OverallScore,
    string QualityStatus,
    string Trend,
    string Title,
    string Description,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string[] MetricRefs);

public sealed record UpdateAssurArrStatusRequest(string Status, string? ClosureSummary = null);
