namespace AssurArr.Api.Contracts;

public sealed record AssurArrDashboardCardResponse(
    string Key,
    string Title,
    string Description,
    int Count,
    string Tone);

public sealed record AssurArrTimelineEventResponse(
    Guid Id,
    string SubjectType,
    Guid SubjectId,
    string EventType,
    string? Details,
    DateTimeOffset OccurredAt);

public sealed record AssurArrDashboardResponse(
    DateTimeOffset GeneratedAt,
    IReadOnlyList<AssurArrDashboardCardResponse> Cards,
    IReadOnlyList<AssurArrTimelineEventResponse> RecentEvents);

public sealed record AssurArrListItemResponse(
    Guid Id,
    string Number,
    string Title,
    string Status,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record AssurArrNonconformanceResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string NonconformanceType,
    string Category,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string? CustomerImpact,
    string? SupplierImpact,
    string? SafetyImpact,
    string? ComplianceImpact,
    bool RecurrenceFlag,
    string? RepeatOfNonconformanceRef,
    DateTimeOffset? DueAt);

public sealed record CreateAssurArrNonconformanceRequest(
    string Title,
    string Description,
    string Severity,
    string NonconformanceType,
    string Category,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string? CustomerImpact,
    string? SupplierImpact,
    string? SafetyImpact,
    string? ComplianceImpact,
    bool RecurrenceFlag,
    string? RepeatOfNonconformanceRef,
    DateTimeOffset? DueAt);

public sealed record AssurArrQualityHoldResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string HoldType,
    string HoldScope,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string? HoldReason,
    string? ReleaseReason,
    string? RejectionReason,
    string? ConditionalReleaseTerms,
    decimal? QuantityHeld,
    string? UnitOfMeasure,
    string? LotNumber,
    string? SerialNumber,
    DateTimeOffset? PlacedAt,
    Guid? PlacedByPersonId,
    DateTimeOffset? ReleasedAt,
    Guid? ReleasedByPersonId,
    DateTimeOffset? ExpiresAt);

public sealed record CreateAssurArrQualityHoldRequest(
    string Title,
    string Description,
    string Severity,
    string HoldType,
    string HoldScope,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string? HoldReason,
    decimal? QuantityHeld,
    string? UnitOfMeasure,
    string? LotNumber,
    string? SerialNumber,
    DateTimeOffset? ExpiresAt);

public sealed record AssurArrCapaResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string CapaType,
    string SourceType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    Guid? SponsorPersonId,
    string? RootCauseSummary,
    DateTimeOffset? DueAt,
    IReadOnlyList<string> RelatedNonconformanceRefs,
    IReadOnlyList<string> RelatedAuditFindingRefs);

public sealed record CreateAssurArrCapaRequest(
    string Title,
    string Description,
    string Severity,
    string CapaType,
    string SourceType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    Guid? SponsorPersonId,
    string? RootCauseSummary,
    DateTimeOffset? DueAt,
    string[] RelatedNonconformanceRefs,
    string[] RelatedAuditFindingRefs);

public sealed record AssurArrQualityAuditResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string AuditType,
    string? AuditScope,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    IReadOnlyList<string> AuditorPersonIds,
    Guid? LeadAuditorPersonId,
    Guid? StaffArrSiteId,
    Guid? StaffArrLocationId,
    string? SupplierRef,
    string? CustomerRef,
    DateTimeOffset? PlannedStartAt,
    DateTimeOffset? PlannedEndAt,
    DateTimeOffset? ActualStartAt,
    DateTimeOffset? ActualEndAt,
    IReadOnlyList<string> ChecklistRefs,
    IReadOnlyList<string> FindingRefs);

public sealed record CreateAssurArrQualityAuditRequest(
    string Title,
    string Description,
    string Severity,
    string AuditType,
    string? AuditScope,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string[] AuditorPersonIds,
    Guid? LeadAuditorPersonId,
    Guid? StaffArrSiteId,
    Guid? StaffArrLocationId,
    string? SupplierRef,
    string? CustomerRef,
    DateTimeOffset? PlannedStartAt,
    DateTimeOffset? PlannedEndAt,
    string[] ChecklistRefs);

public sealed record AssurArrQualityAuditChecklistResponse(
    Guid Id,
    string Number,
    Guid AuditId,
    string Title,
    string Description,
    string Status,
    IReadOnlyList<string> ItemRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary);

public sealed record CreateAssurArrQualityAuditChecklistRequest(
    string Title,
    string Description,
    string Status);

public sealed record AssurArrQualityAuditChecklistItemResponse(
    Guid Id,
    string Number,
    Guid ChecklistId,
    int Sequence,
    string Prompt,
    string? HelpText,
    string? RequirementRef,
    string ResponseType,
    bool Required,
    string? ResponseValue,
    string? Result,
    bool FindingCreated,
    string? FindingRef,
    IReadOnlyList<string> EvidenceRecordRefs,
    DateTimeOffset? AnsweredAt,
    Guid? AnsweredByPersonId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record CreateAssurArrQualityAuditChecklistItemRequest(
    int Sequence,
    string Prompt,
    string? HelpText,
    string? RequirementRef,
    string ResponseType,
    bool Required,
    string? ResponseValue,
    string? Result,
    bool FindingCreated,
    string? FindingRef,
    string[] EvidenceRecordRefs,
    Guid? AnsweredByPersonId,
    DateTimeOffset? AnsweredAt);

public sealed record UpdateAssurArrQualityAuditChecklistItemResponseRequest(
    string? ResponseValue,
    string? Result,
    bool FindingCreated,
    string? FindingRef,
    string[] EvidenceRecordRefs,
    Guid? AnsweredByPersonId,
    DateTimeOffset? AnsweredAt);

public sealed record AssurArrAuditFindingResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string FindingType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string? AuditRef,
    string? NonconformanceRef,
    string? CapaRef,
    DateTimeOffset? DueAt);

public sealed record CreateAssurArrAuditFindingRequest(
    string Title,
    string Description,
    string Severity,
    string FindingType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string? AuditRef,
    string? NonconformanceRef,
    string? CapaRef,
    DateTimeOffset? DueAt);

public sealed record AssurArrQualityStatusSnapshotResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string TargetProduct,
    string TargetObjectRef,
    string QualityStatus,
    IReadOnlyList<string> ActiveHoldRefs,
    IReadOnlyList<string> OpenNonconformanceRefs,
    IReadOnlyList<string> OpenCapaRefs,
    IReadOnlyList<string> OpenFindingRefs,
    DateTimeOffset? LastReviewedAt,
    Guid? ReviewedByPersonId,
    DateTimeOffset? ExpiresAt);

public sealed record CreateAssurArrQualityStatusSnapshotRequest(
    string TargetProduct,
    string TargetObjectRef,
    string QualityStatus,
    string Severity,
    string Title,
    string Description,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string[] ActiveHoldRefs,
    string[] OpenNonconformanceRefs,
    string[] OpenCapaRefs,
    string[] OpenFindingRefs,
    DateTimeOffset? ExpiresAt);

public sealed record AssurArrQualityScorecardResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string TargetType,
    string TargetRef,
    DateTimeOffset PeriodStart,
    DateTimeOffset PeriodEnd,
    decimal? OverallScore,
    string QualityStatus,
    string Trend,
    DateTimeOffset GeneratedAt,
    string GeneratedBy,
    Guid? ReviewedByPersonId,
    DateTimeOffset? ReviewedAt,
    IReadOnlyList<string> MetricRefs);

public sealed record AssurArrQualityReviewResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string ReviewType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string? SourceReviewRef,
    Guid? ReviewerPersonId,
    DateTimeOffset? RequestedAt,
    DateTimeOffset? DueAt,
    DateTimeOffset? DecisionAt,
    string? DecisionReason,
    IReadOnlyList<string> RequiredEvidenceRefs,
    IReadOnlyList<string> SubmittedEvidenceRefs,
    string? Notes);

public sealed record CreateAssurArrQualityReviewRequest(
    string Title,
    string Description,
    string Severity,
    string ReviewType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string? SourceReviewRef,
    Guid? ReviewerPersonId,
    DateTimeOffset? RequestedAt,
    DateTimeOffset? DueAt,
    string? DecisionReason,
    string[] RequiredEvidenceRefs,
    string[] SubmittedEvidenceRefs,
    string? Notes);

public sealed record AssurArrQualityReleaseResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    Guid? OwnerPersonId,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    string HoldRef,
    string ReleaseType,
    Guid? RequestedByPersonId,
    DateTimeOffset? RequestedAt,
    Guid? ApprovedByPersonId,
    DateTimeOffset? ApprovedAt,
    DateTimeOffset? ExecutedAt,
    string? Conditions,
    DateTimeOffset? ExpirationAt,
    IReadOnlyList<string> EvidenceRecordRefs,
    string? Notes);

public sealed record CreateAssurArrQualityReleaseRequest(
    string Title,
    string Description,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string HoldRef,
    string ReleaseType,
    Guid? RequestedByPersonId,
    DateTimeOffset? RequestedAt,
    string? Conditions,
    DateTimeOffset? ExpirationAt,
    string[] EvidenceRecordRefs,
    string? Notes);

public sealed record AssurArrContainmentActionResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string ActionType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    string? NonconformanceRef,
    Guid? AssignedPersonId,
    string? AssignedTeamRef,
    string? SourceProductActionRef,
    DateTimeOffset? DueAt,
    DateTimeOffset? StartedAt,
    DateTimeOffset? CompletedAt,
    Guid? CompletedByPersonId,
    bool VerificationRequired,
    Guid? VerifiedByPersonId,
    DateTimeOffset? VerifiedAt,
    IReadOnlyList<string> EvidenceRecordRefs,
    string? Notes,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary);

public sealed record CreateAssurArrContainmentActionRequest(
    string Title,
    string Description,
    string Severity,
    string ActionType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    string? NonconformanceRef,
    Guid? AssignedPersonId,
    string? AssignedTeamRef,
    string? SourceProductActionRef,
    DateTimeOffset? DueAt,
    bool VerificationRequired,
    string[] EvidenceRecordRefs,
    string? Notes);

public sealed record AssurArrDispositionResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string DispositionType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    string? NonconformanceRef,
    Guid? DecisionByPersonId,
    DateTimeOffset? DecisionAt,
    Guid? ApprovedByPersonId,
    DateTimeOffset? ApprovedAt,
    string? Rationale,
    IReadOnlyList<string> RequiredActions,
    string? ExecutionProduct,
    string? ExecutionObjectRef,
    IReadOnlyList<string> EvidenceRecordRefs,
    string? Notes,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary);

public sealed record CreateAssurArrDispositionRequest(
    string Title,
    string Description,
    string Severity,
    string DispositionType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    string? NonconformanceRef,
    Guid? DecisionByPersonId,
    DateTimeOffset? DecisionAt,
    Guid? ApprovedByPersonId,
    DateTimeOffset? ApprovedAt,
    string? Rationale,
    string[] RequiredActions,
    string? ExecutionProduct,
    string? ExecutionObjectRef,
    string[] EvidenceRecordRefs,
    string? Notes);

public sealed record AssurArrSupplierQualityIssueResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string IssueType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    IReadOnlyList<string> AffectedReceiptRefs,
    IReadOnlyList<string> AffectedPurchaseOrderRefs,
    IReadOnlyList<string> AffectedItemRefs,
    string? SupplierRef,
    string? NonconformanceRef,
    string? ScarRef,
    IReadOnlyList<string> HoldRefs,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    Guid? OwnerPersonId,
    DateTimeOffset? OpenedAt);

public sealed record CreateAssurArrSupplierQualityIssueRequest(
    string Title,
    string Description,
    string Severity,
    string IssueType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedReceiptRefs,
    string[] AffectedPurchaseOrderRefs,
    string[] AffectedItemRefs,
    string? SupplierRef,
    string? NonconformanceRef,
    string? ScarRef,
    string[] HoldRefs,
    string[] RecordRefs,
    Guid? OwnerPersonId,
    DateTimeOffset? OpenedAt);

public sealed record AssurArrCustomerComplaintQualityCaseResponse(
    Guid Id,
    string Number,
    string Title,
    string Description,
    string Status,
    string Severity,
    string ComplaintType,
    string? SourceProduct,
    string? SourceObjectRef,
    IReadOnlyList<string> AffectedObjectRefs,
    IReadOnlyList<string> AffectedOrderRefs,
    IReadOnlyList<string> AffectedShipmentRefs,
    IReadOnlyList<string> AffectedItemRefs,
    IReadOnlyList<string> AffectedAssetRefs,
    string? CustomerRef,
    string? CustomerContactSnapshot,
    string? CustomerLocationRef,
    string? NonconformanceRef,
    IReadOnlyList<string> HoldRefs,
    IReadOnlyList<string> CapaRefs,
    IReadOnlyList<string> CustomerResponseRecordRefs,
    IReadOnlyList<string> RecordRefs,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ClosedAt,
    Guid? ClosedByPersonId,
    string? ClosureSummary,
    Guid? OwnerPersonId,
    DateTimeOffset? ReceivedAt,
    Guid? ReceivedByPersonId,
    DateTimeOffset? CustomerResponseDueAt);

public sealed record CreateAssurArrCustomerComplaintQualityCaseRequest(
    string Title,
    string Description,
    string Severity,
    string ComplaintType,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedOrderRefs,
    string[] AffectedShipmentRefs,
    string[] AffectedItemRefs,
    string[] AffectedAssetRefs,
    string? CustomerRef,
    string? CustomerContactSnapshot,
    string? CustomerLocationRef,
    string? NonconformanceRef,
    string[] HoldRefs,
    string[] CapaRefs,
    string[] CustomerResponseRecordRefs,
    string[] RecordRefs,
    Guid? OwnerPersonId,
    DateTimeOffset? ReceivedAt,
    Guid? ReceivedByPersonId,
    DateTimeOffset? CustomerResponseDueAt);

public sealed record CreateAssurArrQualityScorecardRequest(
    string TargetType,
    string TargetRef,
    DateTimeOffset PeriodStart,
    DateTimeOffset PeriodEnd,
    decimal? OverallScore,
    string QualityStatus,
    string Trend,
    string Title,
    string Description,
    string Severity,
    string? SourceProduct,
    string? SourceObjectRef,
    string[] AffectedObjectRefs,
    Guid? OwnerPersonId,
    string[] MetricRefs);

public sealed record UpdateAssurArrStatusRequest(string Status, string? ClosureSummary = null);
