namespace RecordArr.Api.Models;

public sealed record RecordArrSessionResponse(
    string UserId,
    string PersonId,
    string TenantId,
    string SessionId,
    string TenantRoleKey,
    bool IsPlatformAdmin,
    string ProductKey,
    IReadOnlyCollection<string> LaunchableProductKeys);

public sealed record RecordArrDashboardResponse(
    DateTimeOffset GeneratedAt,
    int RecordCount,
    int ActiveCount,
    int ReviewCount,
    int UploadSessionCount,
    int PackageCount,
    int ControlledDocumentCount,
    int LegalHoldCount,
    IReadOnlyList<RecordArrRecordResponse> RecentRecords,
    IReadOnlyList<RecordArrPackageResponse> OpenPackages,
    IReadOnlyList<RecordArrControlledDocumentResponse> ControlledDocuments,
    IReadOnlyList<RecordArrLegalHoldResponse> LegalHolds);

public sealed record RecordArrRecordResponse(
    string RecordId,
    string RecordNumber,
    string Title,
    string Description,
    string RecordType,
    string DocumentClass,
    string DocumentType,
    string DocumentSubtype,
    string Status,
    string Classification,
    string SourceProduct,
    string SourceObjectType,
    string SourceObjectId,
    string SourceObjectDisplayName,
    string OwnerPersonId,
    string? UploadedByPersonId,
    DateTimeOffset UploadedAt,
    DateTimeOffset? EffectiveAt,
    DateTimeOffset? ExpiresAt,
    string CurrentFileName,
    string CurrentMimeType,
    int VersionNumber,
    IReadOnlyList<string> Tags,
    string CurrentFileRef,
    IReadOnlyList<string> FileRefs,
    string CurrentVersionRef,
    IReadOnlyList<string> SourceObjectRefs,
    IReadOnlyList<string> MetadataRefs,
    IReadOnlyList<string> VersionRefs,
    IReadOnlyList<string> OcrResultRefs,
    IReadOnlyList<string> ExtractionResultRefs,
    IReadOnlyList<string> EvidenceMappingRefs,
    IReadOnlyList<string> PackageRefs,
    string? RetentionPolicyRef,
    string? RetentionStatusRef,
    IReadOnlyList<string> LegalHoldRefs,
    string? AccessPolicyRef,
    IReadOnlyList<string> ComplianceRefs,
    IReadOnlyList<RecordArrAuditTrailEntryResponse> AuditTrail,
    DateTimeOffset? ArchivedAt = null,
    DateTimeOffset? PurgedAt = null)
{
    public RecordArrRecordRefResponse? RecordRef { get; init; }
}

public sealed record RecordArrRecordRefResponse(
    string RecordarrRecordId,
    string RecordNumberSnapshot,
    string TitleSnapshot,
    string RecordTypeSnapshot,
    string DocumentClassSnapshot,
    string DocumentTypeSnapshot,
    string DocumentSubtypeSnapshot,
    string StatusSnapshot,
    string ClassificationSnapshot,
    int VersionSnapshot,
    DateTimeOffset? ExpiresAtSnapshot,
    string? RetentionStatusSnapshot,
    DateTimeOffset LastResolvedAt);

public sealed record RecordArrFileRenditionResponse(
    string RenditionId,
    string FileId,
    string RecordId,
    string RenditionType,
    string StorageKey,
    string MimeType,
    long SizeBytes,
    int? PageCount,
    string Status,
    DateTimeOffset GeneratedAt);

public sealed record RecordArrFileResponse(
    string FileId,
    string TenantId,
    string RecordId,
    string FileNumber,
    string StorageProvider,
    string StorageKey,
    string OriginalFilename,
    string NormalizedFilename,
    string Extension,
    string MimeType,
    long SizeBytes,
    string ChecksumSha256,
    int? PageCount,
    int? ImageWidth,
    int? ImageHeight,
    int? DurationSeconds,
    DateTimeOffset UploadedAt,
    string UploadedByPersonId,
    string VirusScanStatus,
    string ProcessingStatus,
    string EncryptionStatus,
    DateTimeOffset? DeletedAt,
    string? DeleteReason,
    IReadOnlyList<RecordArrFileRenditionResponse> Renditions);

public sealed record RecordArrFileIntegrityCheckResponse(
    string IntegrityCheckId,
    string TenantId,
    string FileId,
    string RecordId,
    string StorageProvider,
    string StorageKey,
    string ExpectedChecksumSha256,
    string ObservedChecksumSha256,
    string Status,
    string CheckMethod,
    DateTimeOffset CheckedAt,
    string CheckedByPersonId,
    string? FailureReason);

public sealed record RecordArrFileMalwareScanResponse(
    string MalwareScanId,
    string TenantId,
    string FileId,
    string RecordId,
    string StorageProvider,
    string StorageKey,
    string Status,
    string ScannerName,
    string? ScannerVersion,
    string? SignatureVersion,
    string? ThreatName,
    string QuarantineStatus,
    DateTimeOffset ScannedAt,
    string ScannedByPersonId,
    string? FailureReason);

public sealed record RecordArrMalwareScanRunResponse(
    string MalwareScanRunId,
    string TenantId,
    string ScannerName,
    string? ScannerVersion,
    string? SignatureVersion,
    DateTimeOffset StartedAt,
    DateTimeOffset CompletedAt,
    string RequestedByPersonId,
    int PendingFileCount,
    int ScannedFileCount,
    int ReleasedFileCount,
    int QuarantinedFileCount,
    int FailedFileCount,
    IReadOnlyList<string> ReleasedFileRefs,
    IReadOnlyList<string> QuarantinedFileRefs,
    IReadOnlyList<string> FailedFileRefs,
    IReadOnlyList<RecordArrFileMalwareScanResponse> ScanResults);

public sealed record RecordArrMalwareScanProviderVerdict(
    string FileId,
    string Status,
    string? ThreatName,
    string? FailureReason);

public sealed record RecordArrMalwareScanDeadLetterRunResponse(
    string DeadLetterRunId,
    string TenantId,
    DateTimeOffset StartedAt,
    DateTimeOffset CompletedAt,
    string RequestedByPersonId,
    int EligibleFailedFileCount,
    int DeadLetteredFileCount,
    IReadOnlyList<string> DeadLetteredFileRefs,
    IReadOnlyList<RecordArrFileMalwareScanResponse> DeadLetterResults);

public sealed record RecordArrStorageReconciliationResponse(
    string ReconciliationId,
    string TenantId,
    string Scope,
    string Status,
    DateTimeOffset StartedAt,
    DateTimeOffset CompletedAt,
    string RequestedByPersonId,
    int TotalFiles,
    int CheckedFiles,
    int PassedFiles,
    int MissingFiles,
    int CorruptFiles,
    int QuarantinedFiles,
    int PendingScanFiles,
    int DeletedFiles,
    IReadOnlyList<string> IssueFileRefs,
    string? IssueSummary,
    string RemediationStatus);

public sealed record RecordArrStorageReconciliationRemediationResponse(
    string ReconciliationId,
    string TenantId,
    string RemediationStatus,
    DateTimeOffset RemediatedAt,
    string RemediatedByPersonId,
    IReadOnlyList<string> ResolvedFileRefs,
    IReadOnlyList<string> RemainingIssueFileRefs,
    RecordArrStorageReconciliationResponse Reconciliation);

public sealed record RecordArrObjectStoreObjectResponse(
    string ObjectStoreObjectId,
    string TenantId,
    string FileId,
    string RecordId,
    string StorageProvider,
    string StorageKey,
    long SizeBytes,
    string ExpectedChecksumSha256,
    string? LastObservedChecksumSha256,
    string Status,
    string LastObservationSource,
    string? LastIntegrityCheckRef,
    string? LastReconciliationRef,
    DateTimeOffset LastObservedAt,
    string LastObservedByPersonId,
    string? FailureReason,
    string? LifecycleStatus = null,
    string? LifecycleProviderName = null,
    string? LifecyclePolicyRef = null,
    string? LifecycleRetentionMode = null,
    DateTimeOffset? LifecycleRetainUntil = null,
    string? LifecycleEncryptionKeyRef = null,
    string? LifecycleEvidenceRef = null,
    string? LifecycleEvidenceHash = null,
    string? LifecycleFailureReason = null);

public sealed record RecordArrObjectStoreFixityObservationResponse(
    string FixityObservationId,
    string TenantId,
    string FileId,
    string RecordId,
    string StorageProvider,
    string StorageKey,
    long SizeBytes,
    string ExpectedChecksumSha256,
    string? ObservedChecksumSha256,
    string Status,
    string ObservationSource,
    string? IntegrityCheckRef,
    string? ReconciliationRef,
    DateTimeOffset ObservedAt,
    string ObservedByPersonId,
    string? FailureReason,
    string? LifecycleStatus = null,
    string? LifecycleProviderName = null,
    string? LifecyclePolicyRef = null,
    string? LifecycleRetentionMode = null,
    DateTimeOffset? LifecycleRetainUntil = null,
    string? LifecycleEncryptionKeyRef = null,
    string? LifecycleEvidenceRef = null,
    string? LifecycleEvidenceHash = null);

public sealed record RecordArrObjectStoreLifecycleVerificationResponse(
    string ObjectStoreObjectId,
    string TenantId,
    string FileId,
    string RecordId,
    string Status,
    string ProviderName,
    string PolicyRef,
    string RetentionMode,
    DateTimeOffset RetainUntil,
    string EncryptionKeyRef,
    string EvidenceRef,
    string EvidenceHash,
    string? FailureReason,
    RecordArrObjectStoreObjectResponse ObjectStoreObject);

public sealed record RecordArrObjectStoreInventoryResult(
    string? Scope,
    string? RecordId,
    IReadOnlyList<string>? VerifiedFileIds,
    IReadOnlyList<string>? MissingFileIds,
    IReadOnlyList<string>? CorruptFileIds,
    IReadOnlyList<string>? RestoredFileIds,
    IReadOnlyList<string>? AcceptedMissingFileIds,
    IReadOnlyList<string>? RecheckedCorruptFileIds,
    IReadOnlyList<string>? ReleasedQuarantinedFileIds,
    IReadOnlyList<string>? ScannedPendingFileIds);

public sealed record RecordArrDisasterRecoveryRunResponse(
    string DisasterRecoveryRunId,
    string TenantId,
    string RunType,
    string Scope,
    string RecoveryPointId,
    DateTimeOffset RecoveryPointCreatedAt,
    DateTimeOffset StartedAt,
    DateTimeOffset CompletedAt,
    string RequestedByPersonId,
    string Status,
    int RpoTargetMinutes,
    int RtoTargetMinutes,
    int RecoveryPointAgeMinutes,
    int DurationSeconds,
    bool RpoMet,
    bool RtoMet,
    int TotalRecordCount,
    int RestoredRecordCount,
    int BlockedRecordCount,
    int TotalFileCount,
    int VerifiedFileCount,
    int FailedFileCount,
    IReadOnlyList<string> RestoredRecordRefs,
    IReadOnlyList<string> BlockedRecordRefs,
    IReadOnlyList<string> VerifiedFileRefs,
    IReadOnlyList<string> FailedFileRefs,
    string? EvidenceSummary,
    string? FailureReason,
    string? BackupProviderName = null,
    string? BackupJobRef = null,
    string? BackupManifestHash = null);

public sealed record RecordArrUploadSessionResponse(
    string UploadSessionId,
    string TenantId,
    string UploadSessionNumber,
    string SessionType,
    string SourceProduct,
    string SourceObjectType,
    string SourceObjectId,
    string UploadPurpose,
    string Status,
    bool RequiresDocumentScan,
    bool RequiresOcr,
    bool RequiresManualReview,
    DateTimeOffset CreatedAt,
    DateTimeOffset ExpiresAt,
    DateTimeOffset? CompletedAt,
    DateTimeOffset? RevokedAt,
    IReadOnlyList<string> AllowedMimeTypes,
    int MaxUploads,
    long MaxFileSizeBytes,
    IReadOnlyList<string> UploadedRecordRefs);

public sealed record RecordArrCaptureRequestResponse(
    string CaptureRequestId,
    string TenantId,
    string SourceProduct,
    string SourceObjectRef,
    string CaptureType,
    string Title,
    string Instructions,
    bool Required,
    string Status,
    string? UploadSessionRef,
    string? EvidenceRequirementRef,
    DateTimeOffset CreatedAt,
    DateTimeOffset? CompletedAt);

public sealed record RecordArrEdgeDetectionResultResponse(
    string EdgeDetectionResultId,
    string ScanProcessingId,
    string Status,
    decimal ConfidenceScore,
    int PageIndex,
    string? Corners,
    DateTimeOffset DetectedAt,
    bool RequiresManualCorrection);

public sealed record RecordArrImageEnhancementSettingsResponse(
    string SettingsId,
    string ScanProcessingId,
    bool CropApplied,
    bool PerspectiveCorrectionApplied,
    bool ContrastAdjusted,
    bool BrightnessAdjusted,
    bool GrayscaleApplied,
    bool NoiseReductionApplied,
    bool SharpenApplied,
    bool BackgroundCleaned,
    string OutputFormat);

public sealed record RecordArrScanProcessingResponse(
    string ScanProcessingId,
    string RecordId,
    string OriginalFileName,
    string Status,
    string ScanPurpose,
    string? EdgeCoordinates,
    string? ManualEdgeCoordinates,
    string? CorrectedByPersonId,
    DateTimeOffset? CorrectedAt,
    string? OriginalFileRef,
    string? GeneratedPdfFileRef,
    string? GeneratedPdfRecordRef,
    string? OcrResultId,
    string? ExtractionResultId,
    RecordArrEdgeDetectionResultResponse? EdgeDetectionResult,
    RecordArrImageEnhancementSettingsResponse? EnhancementSettings,
    decimal ConfidenceScore,
    DateTimeOffset? ProcessedAt,
    string? FailureReason);

public sealed record RecordArrOcrPageResultResponse(
    string PageResultId,
    string OcrResultId,
    int PageNumber,
    string Text,
    decimal ConfidenceScore,
    int Width,
    int Height,
    IReadOnlyList<string> Blocks);

public sealed record RecordArrOcrResultResponse(
    string OcrResultId,
    string RecordId,
    string FileId,
    string Engine,
    string Status,
    string Language,
    decimal ConfidenceScore,
    string FullText,
    IReadOnlyList<RecordArrOcrPageResultResponse> PageResults,
    IReadOnlyList<string> BlockResults,
    DateTimeOffset ExtractedAt,
    string? FailureReason);

public sealed record RecordArrExtractedFieldResponse(
    string ExtractedFieldId,
    string ExtractionResultId,
    string FieldKey,
    string Label,
    string Value,
    string ValueType,
    decimal ConfidenceScore,
    int? PageNumber,
    string? BoundingBox,
    string ReviewStatus,
    string? CorrectedValue,
    string? CorrectedByPersonId,
    DateTimeOffset? CorrectedAt);

public sealed record RecordArrExtractionResultResponse(
    string ExtractionResultId,
    string RecordId,
    string ExtractionType,
    string Status,
    IReadOnlyList<RecordArrExtractedFieldResponse> ExtractedFields,
    decimal ConfidenceScore,
    DateTimeOffset ExtractedAt,
    string? ReviewedByPersonId,
    DateTimeOffset? ReviewedAt,
    string? FailureReason);

public sealed record RecordArrEvidenceMappingResponse(
    string EvidenceMappingId,
    string RecordId,
    string SourceProduct,
    string SourceObjectType,
    string SourceObjectId,
    string ComplianceRequirementRef,
    string EvidenceTypeKey,
    string Status,
    string MappingSource,
    decimal ConfidenceScore,
    string? ConfirmedByPersonId,
    DateTimeOffset? ConfirmedAt,
    string? RejectedByPersonId,
    DateTimeOffset? RejectedAt,
    string? RejectionReason,
    string? Notes);

public sealed record RecordArrEvidenceCoverageResponse(
    string EvidenceCoverageId,
    string TenantId,
    string SourceProduct,
    string SourceObjectRef,
    string ComplianceCoreRequirementRef,
    string Status,
    IReadOnlyList<string> RecordRefs,
    IReadOnlyList<string> MissingEvidenceTypes,
    IReadOnlyList<string> InvalidRecordRefs,
    DateTimeOffset EvaluatedAt,
    string EvaluationRef);

public sealed record RecordArrPackageResponse(
    string PackageId,
    string PackageNumber,
    string Title,
    string PackageType,
    string Status,
    string SourceProduct,
    IReadOnlyList<string> SourceObjectRefs,
    IReadOnlyList<string> RecordRefs,
    string? ManifestChecksum,
    string? GeneratedPdfRecordRef,
    string? GeneratedZipFileRef,
    DateTimeOffset CreatedAt,
    DateTimeOffset? CompletedAt,
    DateTimeOffset? LockedAt,
    DateTimeOffset? ArchivedAt,
    DateTimeOffset? ExpiresAt);

public sealed record RecordArrPackageManifestResponse(
    string ManifestId,
    string PackageId,
    int ManifestVersion,
    DateTimeOffset GeneratedAt,
    IReadOnlyList<RecordArrPackageManifestEntryResponse> RecordEntries,
    IReadOnlyList<RecordArrPackageManifestEntryResponse> SourceObjectEntries,
    IReadOnlyList<RecordArrPackageManifestEntryResponse> RequirementEntries,
    string Checksum,
    string GeneratedByPersonId);

public sealed record RecordArrPackageManifestEntryResponse(
    string EntryId,
    string EntryType,
    string DisplayName,
    string? SourceProduct,
    string? SourceObjectRef,
    string? RecordRef,
    string? ComplianceRequirementRef,
    string? StatusSnapshot,
    string Checksum);

public sealed record RecordArrRecordMetadataResponse(
    string MetadataId,
    string RecordId,
    string Key,
    string Value,
    string ValueType,
    string Source,
    decimal ConfidenceScore,
    bool Verified,
    string? VerifiedByPersonId,
    DateTimeOffset? VerifiedAt);

public sealed record RecordArrRecordLinkResponse(
    string RecordLinkId,
    string RecordId,
    string? LinkedRecordId,
    string? SourceObjectRef,
    string LinkType,
    DateTimeOffset CreatedAt,
    string CreatedByPersonId);

public sealed record RecordArrRecordCommentResponse(
    string CommentId,
    string RecordId,
    string Body,
    string Visibility,
    DateTimeOffset CreatedAt,
    string CreatedByPersonId,
    DateTimeOffset? EditedAt,
    string? EditedByPersonId);

public sealed record RecordArrRetentionPolicyResponse(
    string RetentionPolicyId,
    string PolicyKey,
    string Title,
    string Description,
    string RecordTypeApplicability,
    string DocumentTypeApplicability,
    string SourceProductApplicability,
    int RetainFor,
    string RetentionUnit,
    string RetentionStartTrigger,
    string DisposalAction,
    bool LegalHoldOverrides,
    string Status,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record RecordArrRetentionStatusResponse(
    string RetentionStatusId,
    string RecordId,
    string RetentionPolicyRef,
    string Status,
    DateTimeOffset RetentionStartAt,
    DateTimeOffset? RetentionExpiresAt,
    DateTimeOffset? NextReviewAt,
    DateTimeOffset? LastReviewedAt,
    string? ReviewedByPersonId,
    string? DisposalReviewRef);

public sealed record RecordArrDisposalReviewResponse(
    string DisposalReviewId,
    string RecordId,
    string RetentionStatusRef,
    string ProposedAction,
    string Status,
    DateTimeOffset RequestedAt,
    string RequestedByPersonId,
    string? ReviewedByPersonId,
    DateTimeOffset? ReviewedAt,
    string? DecisionReason,
    DateTimeOffset? CompletedAt);

public sealed record RecordArrDestructionCertificateResponse(
    string DestructionCertificateId,
    string CertificateNumber,
    string RecordId,
    string RetentionStatusRef,
    string DisposalReviewRef,
    string DispositionAction,
    string Status,
    DateTimeOffset RequestedAt,
    DateTimeOffset ExecutedAt,
    string ExecutedByPersonId,
    IReadOnlyList<string> DeletedFileRefs,
    IReadOnlyList<string> TombstoneRefs,
    string CertificateHash,
    string? FailureReason);

public sealed record RecordArrRetentionSchedulerRunResponse(
    string SchedulerRunId,
    string LeaseId,
    string TenantId,
    DateTimeOffset RanAt,
    string RequestedByPersonId,
    string Status,
    string ExecutionPolicy,
    int EvaluatedRecordCount,
    int EligibleRecordCount,
    int CreatedReviewCount,
    int SkippedExistingReviewCount,
    int BlockedByLegalHoldCount,
    int AutomaticExecutionCount,
    int NotificationMessageCount,
    IReadOnlyList<string> CreatedDisposalReviewRefs,
    IReadOnlyList<string> BlockedRecordRefs,
    IReadOnlyList<string> OutboxMessageRefs,
    string? FailureReason);

public sealed record RecordArrRetentionSchedulerLeaseResponse(
    string LeaseId,
    string TenantId,
    string SchedulerKey,
    string Status,
    DateTimeOffset AcquiredAt,
    DateTimeOffset ExpiresAt,
    DateTimeOffset? ReleasedAt,
    string AcquiredByPersonId,
    string? SchedulerRunId);

public sealed record RecordArrRetentionSchedulerOutboxMessageResponse(
    string OutboxMessageId,
    string TenantId,
    string SchedulerRunId,
    string MessageType,
    string Status,
    string TargetRecordId,
    string? DisposalReviewRef,
    DateTimeOffset CreatedAt,
    string CreatedByPersonId,
    string DeduplicationKey,
    string Title,
    string Message,
    string Severity,
    string ActionRoute,
    string? ErrorMessage,
    int DeliveryAttemptCount,
    DateTimeOffset? LastAttemptAt,
    DateTimeOffset? DeliveredAt,
    string? DeliveredByPersonId,
    string DeliveryChannel,
    string RecipientRef,
    DateTimeOffset? DueAt,
    DateTimeOffset? EscalateAfter,
    int EscalationLevel,
    string? EscalatedToRecipientRef,
    DateTimeOffset? EscalatedAt,
    string? ExternalProviderRef);

public sealed record RecordArrRetentionSchedulerOutboxDeliveryRunResponse(
    string TenantId,
    DateTimeOffset ProcessedAt,
    string RequestedByPersonId,
    int PendingBeforeCount,
    int DeliveredCount,
    int FailedCount,
    IReadOnlyList<string> DeliveredMessageRefs,
    IReadOnlyList<string> FailedMessageRefs);

public sealed record RecordArrRetentionSchedulerOutboxEscalationRunResponse(
    string TenantId,
    DateTimeOffset EscalatedAt,
    string RequestedByPersonId,
    string EscalationRecipientRef,
    int EligibleBeforeCount,
    int EscalatedCount,
    IReadOnlyList<string> EscalatedMessageRefs);

public sealed record RecordArrLegalHoldResponse(
    string LegalHoldId,
    string HoldNumber,
    string Title,
    string Description,
    string Status,
    string HoldType,
    IReadOnlyList<string> ScopeRules,
    IReadOnlyList<string> RecordRefs,
    string SourceProduct,
    string SourceObjectType,
    string SourceObjectId,
    DateTimeOffset CreatedAt,
    string CreatedByPersonId,
    DateTimeOffset? ActivatedAt,
    DateTimeOffset? ReleasedAt,
    string? ReleasedByPersonId,
    string? ReleaseReason);

public sealed record RecordArrControlledDocumentResponse(
    string ControlledDocumentId,
    string DocumentNumber,
    string RecordId,
    string Title,
    string Description,
    string DocumentClass,
    string DocumentType,
    string DocumentSubtype,
    string ControlledDocumentType,
    string Status,
    string OwnerPersonId,
    string DepartmentOrgUnitId,
    string StaffarrSiteId,
    string CurrentVersionId,
    int ReviewIntervalDays,
    DateTimeOffset? NextReviewAt,
    DateTimeOffset? EffectiveAt,
    DateTimeOffset? ExpiresAt,
    string? SupersedesDocumentRef,
    string? SupersededByDocumentRef,
    bool AcknowledgementRequired,
    IReadOnlyList<string> RelatedRecordRefs,
    IReadOnlyList<RecordArrAuditTrailEntryResponse> AuditTrail);

public sealed record RecordArrAuditTrailEntryResponse(
    string AuditTrailEntryId,
    string Action,
    string ActorPersonId,
    DateTimeOffset OccurredAt,
    string Details);

public sealed record RecordArrControlledDocumentVersionResponse(
    string VersionId,
    string ControlledDocumentId,
    int VersionNumber,
    string VersionLabel,
    string Status,
    string FileName,
    DateTimeOffset CreatedAt,
    string CreatedByPersonId,
    DateTimeOffset? SubmittedForReviewAt,
    DateTimeOffset? ApprovedAt,
    string? ApprovedByPersonId,
    DateTimeOffset? EffectiveAt,
    DateTimeOffset? SupersededAt,
    string? ChangeSummary,
    string? PreviousVersionRef,
    string? NextVersionRef,
    string? FileRef);

public sealed record RecordArrDocumentReviewResponse(
    string DocumentReviewId,
    string ControlledDocumentId,
    string VersionId,
    string ReviewType,
    string Status,
    string RequestedByPersonId,
    string ReviewerPersonId,
    DateTimeOffset RequestedAt,
    DateTimeOffset? DueAt,
    DateTimeOffset? ReviewedAt,
    string? DecisionReason,
    string? Comments);

public sealed record RecordArrDocumentDistributionResponse(
    string DistributionId,
    string ControlledDocumentId,
    string VersionId,
    string DistributionType,
    string TargetRef,
    string Status,
    DateTimeOffset? DistributedAt,
    DateTimeOffset? AcknowledgedAt,
    string? AcknowledgementRef);

public sealed record RecordArrDocumentAcknowledgementResponse(
    string AcknowledgementId,
    string ControlledDocumentId,
    string VersionId,
    string PersonId,
    string Status,
    DateTimeOffset? AcknowledgedAt,
    string? SignatureRecordRef,
    string? AttestationText,
    DateTimeOffset? DueAt);

public sealed record RecordArrReminderResponse(
    string ReminderId,
    string ReminderType,
    string Status,
    string Title,
    string Description,
    string? RecordId,
    string? ControlledDocumentId,
    string? VersionId,
    string? PersonId,
    DateTimeOffset? DueAt,
    DateTimeOffset CreatedAt,
    string SourceRef);

public sealed record RecordArrAccessPolicyResponse(
    string AccessPolicyId,
    string RecordId,
    string PolicyType,
    string Status,
    IReadOnlyList<string> ReadRules,
    IReadOnlyList<string> WriteRules,
    IReadOnlyList<string> DownloadRules,
    IReadOnlyList<string> ShareRules,
    IReadOnlyList<string> ExportRules,
    IReadOnlyList<string> PurgeRules);

public sealed record RecordArrAccessGrantResponse(
    string AccessGrantId,
    string RecordId,
    string GranteeType,
    string GranteeRef,
    string Permission,
    string Status,
    string GrantedByPersonId,
    DateTimeOffset GrantedAt,
    DateTimeOffset? ExpiresAt,
    DateTimeOffset? RevokedAt,
    string? RevokeReason);

public sealed record RecordArrExternalShareResponse(
    string ExternalShareId,
    string ShareNumber,
    string RecordId,
    string SharePurpose,
    string Status,
    string RecipientName,
    string RecipientEmail,
    IReadOnlyList<string> AllowedActions,
    DateTimeOffset CreatedAt,
    string CreatedByPersonId,
    DateTimeOffset? ExpiresAt,
    DateTimeOffset? RevokedAt,
    string? RevokedByPersonId,
    DateTimeOffset? LastAccessedAt,
    int AccessCount);

public sealed record RecordArrSignatureRecordResponse(
    string SignatureRecordId,
    string TenantId,
    string RecordId,
    string SignaturePurpose,
    string? SignerPersonId,
    string? SignerExternalName,
    string? SignerTitle,
    string AttestationText,
    string SignatureFileRef,
    DateTimeOffset SignedAt,
    string CapturedByPersonId,
    string SourceProduct,
    string SourceObjectRef,
    string? GeoCoordinates,
    string? DeviceSnapshot,
    string VerificationStatus = "local_capture_only",
    string? ProviderName = null,
    string? ProviderEnvelopeRef = null,
    string? CertificateFingerprintSha256 = null,
    string SignatureEvidenceHash = "",
    DateTimeOffset? LockedAt = null,
    string? VerificationFailureReason = null,
    string? ProviderCallbackStatus = null,
    string? ProviderCallbackRef = null,
    DateTimeOffset? ProviderCallbackReceivedAt = null,
    string? ProviderCallbackEvidenceHash = null,
    string? TrustTimestampAuthorityRef = null,
    string? LongTermValidationStatus = null);

public sealed record RecordArrSignatureProviderReconciliationResponse(
    string SignatureRecordId,
    string TenantId,
    string RecordId,
    string ProviderName,
    string ProviderEnvelopeRef,
    string ProviderCallbackStatus,
    string ProviderCallbackRef,
    DateTimeOffset ProviderCallbackReceivedAt,
    string ProviderCallbackEvidenceHash,
    string VerificationStatus,
    string? VerificationFailureReason,
    string? TrustTimestampAuthorityRef,
    string? LongTermValidationStatus,
    RecordArrSignatureRecordResponse SignatureRecord);

public sealed record RecordArrSignatureTrustServiceJobResponse(
    string TrustServiceJobId,
    string TenantId,
    string SignatureRecordId,
    string RecordId,
    string ProviderName,
    string ProviderEnvelopeRef,
    string Status,
    string RequestedByPersonId,
    DateTimeOffset RequestedAt,
    string CertificateFingerprintSha256,
    string SignatureEvidenceHash,
    string SubmissionEvidenceHash,
    DateTimeOffset? LastSubmittedAt = null,
    string? ProviderCallbackStatus = null,
    string? ProviderCallbackRef = null,
    DateTimeOffset? ProviderCallbackReceivedAt = null,
    string? ProviderCallbackEvidenceHash = null,
    string? TrustTimestampAuthorityRef = null,
    string? LongTermValidationStatus = null,
    string? FailureReason = null,
    RecordArrSignatureRecordResponse? SignatureRecord = null);

public sealed record RecordArrPhotoEvidenceResponse(
    string PhotoEvidenceId,
    string TenantId,
    string RecordId,
    string PhotoPurpose,
    string SourceProduct,
    string SourceObjectRef,
    DateTimeOffset CapturedAt,
    string CapturedByPersonId,
    string? GeoCoordinates,
    string? DeviceSnapshot,
    string? Notes);

public sealed record RecordArrRedactionResponse(
    string RedactionId,
    string SourceRecordId,
    string RedactedRecordId,
    string RedactionReason,
    string Status,
    string RedactedByPersonId,
    DateTimeOffset RedactedAt,
    IReadOnlyList<string> RedactionRules,
    string ReviewStatus = "approved",
    string? ReviewedByPersonId = null,
    DateTimeOffset? ReviewedAt = null,
    string? ApprovalReason = null,
    string RedactionPackageHash = "",
    DateTimeOffset? LockedAt = null,
    string? VerificationFailureReason = null,
    string? ProviderReviewStatus = null,
    string? ProviderName = null,
    string? ProviderJobRef = null,
    string? ProviderCallbackStatus = null,
    string? ProviderCallbackRef = null,
    DateTimeOffset? ProviderCallbackReceivedAt = null,
    string? ProviderPackageHash = null,
    string? ProviderEvidenceHash = null,
    string? ProviderFailureReason = null,
    string? OverlayReviewStatus = null,
    string? OverlayReviewedByPersonId = null,
    DateTimeOffset? OverlayReviewedAt = null,
    IReadOnlyList<string>? OverlayEvidenceRefs = null,
    IReadOnlyList<string>? OverlayIssueRefs = null,
    string? OverlayReviewHash = null,
    string? OverlayFailureReason = null);

public sealed record RecordArrRedactionProviderReconciliationResponse(
    string RedactionId,
    string TenantId,
    string SourceRecordId,
    string RedactedRecordId,
    string ProviderName,
    string ProviderJobRef,
    string ProviderCallbackStatus,
    string ProviderCallbackRef,
    DateTimeOffset ProviderCallbackReceivedAt,
    string ProviderPackageHash,
    string ProviderEvidenceHash,
    string ProviderReviewStatus,
    string? ProviderFailureReason,
    RecordArrRedactionResponse Redaction);

public sealed record RecordArrRedactionProviderJobResponse(
    string ProviderJobId,
    string TenantId,
    string RedactionId,
    string SourceRecordId,
    string RedactedRecordId,
    string ProviderName,
    string ProviderJobRef,
    string Status,
    string RequestedByPersonId,
    DateTimeOffset RequestedAt,
    string RedactionPackageHash,
    IReadOnlyList<string> RedactionRules,
    string SubmissionEvidenceHash,
    DateTimeOffset? LastSubmittedAt = null,
    string? ProviderCallbackStatus = null,
    string? ProviderCallbackRef = null,
    DateTimeOffset? ProviderCallbackReceivedAt = null,
    string? ProviderEvidenceHash = null,
    string? FailureReason = null,
    RecordArrRedactionResponse? Redaction = null);

public sealed record RecordArrRedactionOverlayReviewResponse(
    string RedactionId,
    string TenantId,
    string SourceRecordId,
    string RedactedRecordId,
    string OverlayReviewStatus,
    string ReviewedByPersonId,
    DateTimeOffset ReviewedAt,
    IReadOnlyList<string> OverlayEvidenceRefs,
    IReadOnlyList<string> OverlayIssueRefs,
    string OverlayReviewHash,
    string? OverlayFailureReason,
    RecordArrRedactionResponse Redaction);

public sealed record RecordArrAccessLogResponse(
    string AccessLogId,
    string RecordId,
    string Action,
    string Result,
    string? ActorPersonId,
    string? ActorServiceClientId,
    string? ExternalShareId,
    DateTimeOffset OccurredAt,
    string? SourceIp,
    string? UserAgent,
    string? ReasonCode,
    string? PreviousAccessLogHash = null,
    string AccessLogHash = "");

public sealed record RecordArrAccessHistoryIntegrityReportResponse(
    string TenantId,
    string? RecordId,
    string Status,
    int CheckedAccessLogs,
    string? FirstAccessLogId,
    string? LastAccessLogId,
    IReadOnlyList<string> BrokenAccessLogIds,
    string? IssueSummary,
    DateTimeOffset VerifiedAt);

public sealed record RecordArrAccessHistorySealResponse(
    string AccessHistorySealId,
    string TenantId,
    string? RecordId,
    string Scope,
    int SealedAccessLogCount,
    string? FirstAccessLogId,
    string? SealedThroughAccessLogId,
    string? SealedThroughAccessLogHash,
    string SealHash,
    string Status,
    string SealedByPersonId,
    DateTimeOffset SealedAt,
    DateTimeOffset? VerifiedAt,
    string? IssueSummary,
    string? AnchorStatus = null,
    string? AnchorProviderName = null,
    string? AnchorReference = null,
    DateTimeOffset? AnchoredAt = null,
    string? AnchoredSealHash = null,
    string? AnchorEvidenceHash = null,
    string? AnchorFailureReason = null);

public sealed record RecordArrAuditEventResponse(
    string AuditEventId,
    string TenantId,
    string RecordId,
    string Action,
    string Outcome,
    string ActorType,
    string? ActorPersonId,
    string? ActorServiceClientId,
    string? ExternalShareId,
    DateTimeOffset OccurredAt,
    string? ReasonCode,
    string? CorrelationId,
    string? PreviousEventHash,
    string EventHash);

public sealed record RecordArrAuditIntegrityReportResponse(
    string TenantId,
    string? RecordId,
    string Status,
    int CheckedEvents,
    string? FirstAuditEventId,
    string? LastAuditEventId,
    IReadOnlyList<string> BrokenAuditEventIds,
    string? IssueSummary,
    DateTimeOffset VerifiedAt);

public sealed record RecordArrAuditSealResponse(
    string AuditSealId,
    string TenantId,
    string? RecordId,
    string Scope,
    int SealedEventCount,
    string? FirstAuditEventId,
    string? SealedThroughAuditEventId,
    string? SealedThroughEventHash,
    string SealHash,
    string Status,
    string SealedByPersonId,
    DateTimeOffset SealedAt,
    DateTimeOffset? VerifiedAt,
    string? IssueSummary,
    string? AnchorStatus = null,
    string? AnchorProviderName = null,
    string? AnchorReference = null,
    DateTimeOffset? AnchoredAt = null,
    string? AnchoredSealHash = null,
    string? AnchorEvidenceHash = null,
    string? AnchorFailureReason = null);

public sealed record RecordArrAuditGovernanceReportResponse(
    string TenantId,
    string? RecordId,
    string Status,
    int CheckedEvents,
    int SealCount,
    int VerifiedSealCount,
    int UnsealedEventCount,
    string? FirstAuditEventId,
    string? LastAuditEventId,
    string? LatestSealThroughAuditEventId,
    IReadOnlyList<string> BrokenAuditEventIds,
    IReadOnlyList<string> BrokenAuditSealIds,
    IReadOnlyList<string> UnsealedAuditEventIds,
    string? IssueSummary,
    DateTimeOffset VerifiedAt);
