# syntax=docker/dockerfile:1
ARG PROJECT_PATH
ARG ASSEMBLY_NAME

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG PROJECT_PATH
WORKDIR /src
COPY . .
RUN dotnet restore "${PROJECT_PATH}"
RUN dotnet publish "${PROJECT_PATH}" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
ARG ASSEMBLY_NAME
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT dotnet ${ASSEMBLY_NAME}.dll
