// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StaffArr.Api.Data;

#nullable disable

namespace StaffArr.Api.Migrations
{
    [DbContext(typeof(StaffArrDbContext))]
    [Migration("20260527093953_StaffArrPeopleDirectorySlice")]
    partial class StaffArrPeopleDirectorySlice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("STLCompliance.Shared.Data.PlatformMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("platform_metadata", (string)null);
                });

            modelBuilder.Entity("StaffArr.Api.Entities.OrgUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ParentOrgUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentOrgUnitId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "UnitType", "Name")
                        .IsUnique();

                    b.ToTable("staffarr_org_units", (string)null);
                });

            modelBuilder.Entity("StaffArr.Api.Entities.StaffPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ExternalUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ManagerPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrimaryEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("PrimaryOrgUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManagerPersonId");

                    b.HasIndex("PrimaryOrgUnitId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ExternalUserId")
                        .IsUnique();

                    b.HasIndex("TenantId", "PrimaryEmail");

                    b.ToTable("staffarr_people", (string)null);
                });

            modelBuilder.Entity("StaffArr.Api.Entities.OrgUnit", b =>
                {
                    b.HasOne("StaffArr.Api.Entities.OrgUnit", "ParentOrgUnit")
                        .WithMany()
                        .HasForeignKey("ParentOrgUnitId");

                    b.Navigation("ParentOrgUnit");
                });

            modelBuilder.Entity("StaffArr.Api.Entities.StaffPerson", b =>
                {
                    b.HasOne("StaffArr.Api.Entities.StaffPerson", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerPersonId");

                    b.HasOne("StaffArr.Api.Entities.OrgUnit", "PrimaryOrgUnit")
                        .WithMany()
                        .HasForeignKey("PrimaryOrgUnitId");

                    b.Navigation("Manager");

                    b.Navigation("PrimaryOrgUnit");
                });
#pragma warning restore 612, 618
        }
    }
}
