namespace ComplianceCore.Api.Contracts;

public sealed record ComplianceExceptionExemptionResponse(
    Guid ExceptionExemptionId,
    Guid TenantId,
    string Key,
    string Label,
    string Type,
    string GoverningBody,
    string ProgramKey,
    string PackKey,
    string CitationKey,
    string ApplicabilityKey,
    string AppliesToSubjectKind,
    string AppliesToSourceProduct,
    string AppliesToSourceEntity,
    string EffectType,
    string ConditionLogicJson,
    Guid? RequiredEvidenceOptionGroupId,
    string IssuingAuthority,
    string AuthorizationNumber,
    DateTimeOffset? EffectiveAt,
    DateTimeOffset? ExpiresAt,
    bool Active,
    string Description,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record CreateComplianceExceptionExemptionRequest(
    string Key,
    string Label,
    string Type,
    string EffectType,
    string? GoverningBody = null,
    string? ProgramKey = null,
    string? PackKey = null,
    string? CitationKey = null,
    string? ApplicabilityKey = null,
    string? AppliesToSubjectKind = null,
    string? AppliesToSourceProduct = null,
    string? AppliesToSourceEntity = null,
    string? ConditionLogicJson = null,
    Guid? RequiredEvidenceOptionGroupId = null,
    string? IssuingAuthority = null,
    string? AuthorizationNumber = null,
    DateTimeOffset? EffectiveAt = null,
    DateTimeOffset? ExpiresAt = null,
    bool Active = true,
    string? Description = null);

public sealed record UpdateComplianceExceptionExemptionRequest(
    string? Label = null,
    string? Type = null,
    string? EffectType = null,
    string? GoverningBody = null,
    string? ProgramKey = null,
    string? PackKey = null,
    string? CitationKey = null,
    string? ApplicabilityKey = null,
    string? AppliesToSubjectKind = null,
    string? AppliesToSourceProduct = null,
    string? AppliesToSourceEntity = null,
    string? ConditionLogicJson = null,
    Guid? RequiredEvidenceOptionGroupId = null,
    string? IssuingAuthority = null,
    string? AuthorizationNumber = null,
    DateTimeOffset? EffectiveAt = null,
    DateTimeOffset? ExpiresAt = null,
    bool? Active = null,
    string? Description = null);
