namespace ReportArr.Api.Models;

public sealed record ReportArrHandoffSessionResponse(
    string AccessToken,
    string AccessTokenExpiresAt,
    string UserId,
    string PersonId,
    string Email,
    string DisplayName,
    string TenantId,
    string TenantSlug,
    string TenantDisplayName,
    string SessionId,
    string TenantRoleKey,
    bool IsPlatformAdmin,
    IReadOnlyList<string> Entitlements);

public sealed record ReportArrSessionBootstrapResponse(
    string UserId,
    string PersonId,
    string TenantId,
    string SessionId,
    string TenantRoleKey,
    bool IsPlatformAdmin,
    string ProductKey,
    bool HasReportArrEntitlement,
    IReadOnlyList<string> Entitlements);

public sealed record ReportArrSummaryResponse(
    DateTimeOffset GeneratedAt,
    string FreshnessStatus,
    int DatasetCount,
    int DashboardCount,
    int ReportDefinitionCount,
    int ReportRunCount,
    int KpiCount,
    int AlertCount,
    int AuditPackageCount,
    IReadOnlyList<ReportArrDatasetResponse> RecentDatasets,
    IReadOnlyList<ReportArrDashboardResponse> RecentDashboards,
    IReadOnlyList<ReportArrReportDefinitionResponse> RecentReports,
    IReadOnlyList<ReportArrAlertResponse> RecentAlerts,
    IReadOnlyList<ReportArrAuditPackageResponse> RecentAuditPackages);

public sealed record ReportArrDatasetResponse(
    string DatasetId,
    string DatasetNumber,
    string DatasetKey,
    string Title,
    string Description,
    string DatasetType,
    string Status,
    string RefreshMode,
    string RefreshFrequency,
    string FreshnessStatus,
    IReadOnlyList<string> SourceProducts,
    IReadOnlyList<string> SourceConnectors,
    DateTimeOffset? LastRefreshedAt,
    DateTimeOffset? LastSuccessfulRefreshAt,
    DateTimeOffset? LastFailedRefreshAt,
    string SchemaVersion,
    IReadOnlyList<string> FieldDefinitions,
    string SourceTraceabilityRules,
    string RetentionPolicy,
    string OwnerPersonId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrDatasetFieldResponse(
    string FieldId,
    string DatasetId,
    string FieldKey,
    string DisplayName,
    string Description,
    string DataType,
    string SourceProduct,
    string SourceFieldPath,
    bool AggregationAllowed,
    bool FilterAllowed,
    bool GroupAllowed,
    bool SortAllowed,
    bool PiiSensitive,
    bool Restricted,
    bool ComplianceSensitive,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrSourceConnectorResponse(
    string SourceConnectorId,
    string SourceProduct,
    string ConnectorType,
    string Status,
    string ServiceClientRef,
    DateTimeOffset? LastConnectedAt,
    DateTimeOffset? LastErrorAt,
    string? LastErrorMessage,
    IReadOnlyList<string> SupportedEventTypes,
    IReadOnlyList<string> SupportedDatasets,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrIngestionCursorResponse(
    string IngestionCursorId,
    string SourceConnectorId,
    string SourceProduct,
    string CursorType,
    string CursorValue,
    string? LastEventId,
    DateTimeOffset? LastEventAt,
    DateTimeOffset? LastIngestedAt,
    string Status,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrSourceEventReceiptResponse(
    string SourceEventReceiptId,
    string SourceProduct,
    string SourceEventId,
    string EventType,
    string? SourceObjectRef,
    DateTimeOffset ReceivedAt,
    DateTimeOffset? ProcessedAt,
    string Status,
    string? FailureReason,
    string? CorrelationId,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrReadModelResponse(
    string ReadModelId,
    string ReadModelNumber,
    string ReadModelKey,
    string Title,
    string Description,
    string ReadModelType,
    string Status,
    string PrimaryEntityType,
    string PrimarySourceProduct,
    IReadOnlyList<string> DatasetRefs,
    IReadOnlyList<string> FieldDefinitions,
    IReadOnlyList<string> RefreshJobRefs,
    DateTimeOffset? LastRebuiltAt,
    DateTimeOffset? LastUpdatedAt,
    DateTimeOffset UpdatedAt,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrReadModelRecordResponse(
    string ReadModelRecordId,
    string ReadModelId,
    string PrimaryEntityRef,
    string Data,
    IReadOnlyList<string> SourceTraces,
    string StatusSnapshot,
    DateTimeOffset EffectiveAt,
    DateTimeOffset? LastSourceUpdatedAt,
    DateTimeOffset IngestedAt,
    DateTimeOffset UpdatedAt,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrDatasetLineageResponse(
    string LineageId,
    string DatasetId,
    string SourceProduct,
    string SourceObjectType,
    string SourceFieldPath,
    string DatasetFieldKey,
    string TransformationDescription,
    string Confidence,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrDashboardResponse(
    string DashboardId,
    string DashboardNumber,
    string DashboardKey,
    string Title,
    string Description,
    string DashboardType,
    string Status,
    string OwnerPersonId,
    string DefaultDateRange,
    string FreshnessStatus,
    IReadOnlyList<string> WidgetRefs,
    IReadOnlyList<string> FilterRefs,
    IReadOnlyList<string> DrilldownRefs,
    string AccessPolicyRef,
    DateTimeOffset? LastViewedAt,
    DateTimeOffset CreatedAt,
    string CreatedByPersonId,
    DateTimeOffset UpdatedAt,
    string UpdatedByPersonId,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrDashboardAccessPolicyResponse(
    string AccessPolicyId,
    string DashboardId,
    string Visibility,
    IReadOnlyList<string> AllowedPersonRefs,
    IReadOnlyList<string> AllowedRoleRefs,
    IReadOnlyList<string> AllowedPermissionRefs,
    IReadOnlyList<string> SourceProductRestrictions,
    bool ExportAllowed,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrDashboardFilterResponse(
    string FilterId,
    string DashboardId,
    string FilterKey,
    string Label,
    string FilterType,
    string DatasetFieldKey,
    string DefaultValue,
    string AllowedValuesSource,
    bool Required,
    bool Visible,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrDrilldownDefinitionResponse(
    string DrilldownId,
    string DashboardId,
    string Title,
    string Description,
    string SourceWidgetRef,
    string TargetType,
    string TargetRef,
    IReadOnlyList<string> ParameterMappings,
    IReadOnlyList<string> RequiredPermissionRefs,
    string Status,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrDashboardWidgetResponse(
    string WidgetId,
    string DashboardId,
    string WidgetKey,
    string Title,
    string Description,
    string WidgetType,
    string Status,
    string DatasetRef,
    string ReadModelRef,
    string QueryDefinition,
    IReadOnlyList<string> FilterBindings,
    string DrilldownTargetRef,
    int SortOrder,
    string Layout,
    string VisualizationSettings,
    string FreshnessStatus,
    DateTimeOffset? LastRenderedAt,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrWidgetVisualizationSettingsResponse(
    string WidgetId,
    string ChartType,
    string? XField,
    string? YField,
    string? SeriesField,
    string? GroupField,
    string? ValueField,
    string? LabelField,
    string? DateField,
    IReadOnlyList<string> ColorRuleRefs,
    IReadOnlyList<string> ThresholdRefs,
    string DisplayFormat,
    bool ShowLegend,
    bool ShowDataLabels,
    int MaxRows,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrReportDefinitionResponse(
    string ReportDefinitionId,
    string ReportNumber,
    string ReportKey,
    string Title,
    string Description,
    string ReportType,
    string Status,
    IReadOnlyList<string> DatasetRefs,
    IReadOnlyList<string> ReadModelRefs,
    IReadOnlyList<string> ParameterRefs,
    IReadOnlyList<string> DefaultFilters,
    string LayoutDefinition,
    IReadOnlyList<string> SectionRefs,
    IReadOnlyList<string> ExportFormats,
    string AccessPolicyRef,
    string OwnerPersonId,
    DateTimeOffset CreatedAt,
    string CreatedByPersonId,
    DateTimeOffset UpdatedAt,
    string UpdatedByPersonId,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrReportAccessPolicyResponse(
    string AccessPolicyId,
    string ReportDefinitionId,
    string Visibility,
    IReadOnlyList<string> AllowedPersonRefs,
    IReadOnlyList<string> AllowedRoleRefs,
    IReadOnlyList<string> AllowedPermissionRefs,
    IReadOnlyList<string> SourceProductRestrictions,
    bool ExportAllowed,
    bool ScheduleAllowed,
    bool ExternalDeliveryAllowed,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrReportParameterResponse(
    string ParameterId,
    string ReportDefinitionId,
    string ParameterKey,
    string Label,
    string ParameterType,
    bool Required,
    string DefaultValue,
    string AllowedValuesSource,
    string ValidationRules,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrReportSectionResponse(
    string SectionId,
    string ReportDefinitionId,
    int Sequence,
    string Title,
    string Description,
    string SectionType,
    string DatasetRef,
    string QueryDefinition,
    string LayoutSettings,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrReportRunResponse(
    string ReportRunId,
    string ReportRunNumber,
    string ReportDefinitionId,
    string Title,
    string Status,
    string RequestedByPersonId,
    DateTimeOffset RequestedAt,
    DateTimeOffset? StartedAt,
    DateTimeOffset? CompletedAt,
    IReadOnlyList<string> ParametersUsed,
    IReadOnlyList<string> FiltersUsed,
    string OutputFormat,
    string? OutputRecordRef,
    string? OutputPackageRef,
    int RowCount,
    int WarningCount,
    string? ExportJobId,
    int ErrorCount,
    string? ErrorMessage,
    string FreshnessStatus,
    string SourceTraceSummary,
    string FreshnessSummary,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrReportScheduleResponse(
    string ScheduleId,
    string ScheduleNumber,
    string ReportDefinitionId,
    string Title,
    string Status,
    string Cadence,
    string Timezone,
    string? CronExpression,
    DateTimeOffset? NextRunAt,
    DateTimeOffset? LastRunAt,
    DateTimeOffset? StartsAt,
    DateTimeOffset? EndsAt,
    IReadOnlyList<string> Parameters,
    IReadOnlyList<string> Recipients,
    string DeliveryMethod,
    string CreatedByPersonId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrReportRecipientResponse(
    string RecipientId,
    string ScheduleId,
    string RecipientType,
    string RecipientRef,
    string? Email,
    string DeliveryFormat,
    string Status,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrExportJobResponse(
    string ExportJobId,
    string ExportNumber,
    string ReportRunId,
    string Title,
    string Status,
    string ExportType,
    string ExportFormat,
    string RequestedByPersonId,
    DateTimeOffset RequestedAt,
    DateTimeOffset? StartedAt,
    DateTimeOffset? CompletedAt,
    string? SourceRef,
    string? OutputRecordRef,
    int RowCount,
    long FileSizeBytesSnapshot,
    DateTimeOffset? ExpiresAt,
    string? ErrorMessage,
    DateTimeOffset GeneratedAt,
    DateTimeOffset? DeliveredAt,
    string? RecordArrPackageRef,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrMetricDefinitionResponse(
    string MetricId,
    string MetricKey,
    string Title,
    string Description,
    string MetricType,
    string SourceDatasetRef,
    IReadOnlyList<string> FieldRefs,
    string Formula,
    string FilterDefinition,
    string GroupingOptions,
    string DateField,
    string Status,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrMetricValueResponse(
    string MetricValueId,
    string MetricId,
    DateTimeOffset PeriodStart,
    DateTimeOffset PeriodEnd,
    decimal Value,
    string? GroupKey,
    string? GroupLabel,
    string SourceTraceSummary,
    DateTimeOffset CalculatedAt,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrAnalyticsSnapshotResponse(
    string AnalyticsSnapshotId,
    string SnapshotNumber,
    string SnapshotType,
    string Status,
    DateTimeOffset PeriodStart,
    DateTimeOffset PeriodEnd,
    IReadOnlyList<string> DatasetRefs,
    IReadOnlyList<string> KpiValueRefs,
    IReadOnlyList<string> MetricValueRefs,
    DateTimeOffset GeneratedAt,
    string GeneratedBy,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrTrendAnalysisResponse(
    string TrendAnalysisId,
    string MetricRef,
    string? KpiRef,
    DateTimeOffset PeriodStart,
    DateTimeOffset PeriodEnd,
    string Trend,
    decimal ChangeValue,
    decimal ChangePercent,
    string Confidence,
    string Explanation,
    DateTimeOffset GeneratedAt,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrExceptionQueryResponse(
    string ExceptionQueryId,
    string QueryKey,
    string Title,
    string Description,
    string SourceDatasetRef,
    string Condition,
    string Severity,
    string Status,
    string OwnerPersonId,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrExceptionResultResponse(
    string ExceptionResultId,
    string ExceptionQueryId,
    string SourceObjectRef,
    string Title,
    string Summary,
    string Severity,
    string Status,
    DateTimeOffset DetectedAt,
    string? AcknowledgedByPersonId,
    DateTimeOffset? AcknowledgedAt,
    DateTimeOffset? ResolvedAt,
    string SourceTrace,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrKpiDefinitionResponse(
    string KpiId,
    string KpiNumber,
    string KpiKey,
    string Title,
    string Description,
    string Category,
    string Status,
    string Formula,
    IReadOnlyList<string> SourceDatasetRefs,
    IReadOnlyList<string> SourceMetricRefs,
    decimal? TargetValue,
    decimal? WarningThreshold,
    decimal? CriticalThreshold,
    bool HigherIsBetter,
    string DisplayFormat,
    string OwnerPersonId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrKpiValueResponse(
    string KpiValueId,
    string KpiId,
    DateTimeOffset PeriodStart,
    DateTimeOffset PeriodEnd,
    decimal Value,
    decimal? TargetValueSnapshot,
    decimal? WarningThresholdSnapshot,
    decimal? CriticalThresholdSnapshot,
    string Status,
    string Trend,
    string SourceTraceSummary,
    DateTimeOffset CalculatedAt,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrAlertResponse(
    string AlertId,
    string AlertNumber,
    string Title,
    string Description,
    string AlertType,
    string Status,
    string DatasetRef,
    string MetricRef,
    string Condition,
    string Severity,
    DateTimeOffset? TriggeredAt,
    string? AcknowledgedByPersonId,
    DateTimeOffset? AcknowledgedAt,
    DateTimeOffset? ResolvedAt,
    IReadOnlyList<string> NotificationRefs,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrAuditPackageResponse(
    string AuditReportPackageId,
    string PackageNumber,
    string Title,
    string Description,
    string Status,
    string RequestedByPersonId,
    ReportArrAuditScopeResponse AuditScope,
    IReadOnlyList<string> ComplianceEvaluationRefs,
    IReadOnlyList<string> SourceProductRefs,
    IReadOnlyList<string> SourceObjectRefs,
    string? RecordArrPackageRef,
    IReadOnlyList<string> ReportRunRefs,
    string MissingEvidenceSummary,
    string InvalidEvidenceSummary,
    decimal ReadinessScore,
    DateTimeOffset GeneratedAt,
    DateTimeOffset? LockedAt,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrAuditScopeResponse(
    string AuditScopeId,
    string ScopeType,
    DateTimeOffset? DateRangeStart,
    DateTimeOffset? DateRangeEnd,
    IReadOnlyList<string> ProductFilters,
    IReadOnlyList<string> ObjectRefs,
    IReadOnlyList<string> RulepackRefs,
    IReadOnlyList<string> SiteRefs,
    IReadOnlyList<string> DepartmentRefs,
    bool IncludeEvidence,
    bool IncludeSourceTrace,
    string TenantId = "tenant-reportarr");

public sealed record ReportArrRefreshJobResponse(
    string RefreshJobId,
    string DatasetId,
    string? ReadModelId,
    string RefreshType,
    string Status,
    string RequestedByPersonId,
    DateTimeOffset QueuedAt,
    DateTimeOffset? StartedAt,
    DateTimeOffset? CompletedAt,
    int RecordsProcessed,
    int RecordsCreated,
    int RecordsUpdated,
    int RecordsSkipped,
    int ErrorCount,
    string? ErrorMessage,
    string TenantId = "tenant-reportarr");
