namespace STLCompliance.Shared.Integration;

public sealed record StlIntegrationTokenProfile(
    string ProfileKey,
    string ConsumerService,
    string ConfigurationKey,
    string SourceProductKey,
    IReadOnlyList<string> AllowedProductKeys,
    string ActionScope);

public static class StlIntegrationTokenCatalog
{
    public static IReadOnlyList<StlIntegrationTokenProfile> All { get; } =
    [
        Profile("handoff-staffarr", "staffarr-api", "Handoff__ServiceToken", "staffarr", ["staffarr"], "launch.redeem"),
        Profile(
            "staffarr-trainarr",
            "staffarr-api",
            "TrainArr__ServiceToken",
            "staffarr",
            ["trainarr"],
            "trainarr.incident_remediations.write,trainarr.person_training_history.read"),

        Profile("handoff-trainarr", "trainarr-api", "Handoff__ServiceToken", "trainarr", ["trainarr"], "launch.redeem"),
        Profile(
            "trainarr-staffarr",
            "trainarr-api",
            "StaffArr__ServiceToken",
            "trainarr",
            ["staffarr"],
            "staffarr.training_blockers.write,staffarr.training_acknowledgements.write,staffarr.training_acknowledgements.read,staffarr.certification_grants.write,staffarr.certification_lifecycle.write,staffarr.person.lookup"),
        Profile(
            "trainarr-compliancecore",
            "trainarr-api",
            "ComplianceCore__ServiceToken",
            "trainarr",
            ["compliancecore"],
            "compliancecore.rules.evaluate,compliancecore.citations.read,compliancecore.rulepacks.read"),

        Profile("handoff-maintainarr", "maintainarr-api", "Handoff__ServiceToken", "maintainarr", ["maintainarr"], "launch.redeem"),
        Profile(
            "maintainarr-staffarr",
            "maintainarr-api",
            "StaffArr__ServiceToken",
            "maintainarr",
            ["staffarr"],
            "staffarr.person.lookup"),
        Profile("maintainarr-supplyarr", "maintainarr-api", "SupplyArr__ServiceToken", "maintainarr", ["supplyarr"], "supplyarr.demand_intake.write"),
        Profile(
            "staffarr-maintainarr",
            "staffarr-api",
            "MaintainArr__ServiceToken",
            "staffarr",
            ["maintainarr"],
            "maintainarr.technician_refs.sync"),

        Profile("handoff-supplyarr", "supplyarr-api", "Handoff__ServiceToken", "supplyarr", ["supplyarr"], "launch.redeem"),
        Profile("supplyarr-maintainarr", "supplyarr-api", "MaintainArr__ServiceToken", "supplyarr", ["maintainarr"], "maintainarr.demand_status.write"),
        Profile("supplyarr-routarr", "supplyarr-api", "RoutArr__ServiceToken", "supplyarr", ["routarr"], "routarr.demand_status.write"),
        Profile("supplyarr-trainarr", "supplyarr-api", "TrainArr__ServiceToken", "supplyarr", ["trainarr"], "trainarr.demand_status.write"),
        Profile(
            "supplyarr-staffarr",
            "supplyarr-api",
            "StaffArr__ServiceToken",
            "supplyarr",
            ["staffarr"],
            "staffarr.demand_status.write,staffarr.procurement_approval_authority.read"),
        Profile(
            "supplyarr-compliancecore",
            "supplyarr-api",
            "ComplianceCore__ServiceToken",
            "supplyarr",
            ["compliancecore"],
            "compliancecore.facts.ingest,compliancecore.sources.ingest"),

        Profile("handoff-routarr", "routarr-api", "Handoff__ServiceToken", "routarr", ["routarr"], "launch.redeem"),
        Profile("routarr-trainarr", "routarr-api", "TrainArr__ServiceToken", "routarr", ["trainarr"], "trainarr.qualification_checks.dispatch"),
        Profile("routarr-staffarr", "routarr-api", "StaffArr__ServiceToken", "routarr", ["staffarr"], "staffarr.readiness.dispatch_gate"),
        Profile("routarr-maintainarr", "routarr-api", "MaintainArr__ServiceToken", "routarr", ["maintainarr"], "maintainarr.asset_readiness.dispatch_gate"),
        Profile("routarr-compliancecore", "routarr-api", "ComplianceCore__ServiceToken", "routarr", ["compliancecore"], "compliancecore.workflow.gates.check"),
        Profile("routarr-supplyarr", "routarr-api", "SupplyArr__ServiceToken", "routarr", ["supplyarr"], "supplyarr.demand_intake.write"),

        Profile("trainarr-supplyarr", "trainarr-api", "SupplyArr__ServiceToken", "trainarr", ["supplyarr"], "supplyarr.demand_intake.write"),

        Profile("staffarr-supplyarr", "staffarr-api", "SupplyArr__ServiceToken", "staffarr", ["supplyarr"], "supplyarr.demand_intake.write"),

        Profile("handoff-compliancecore", "compliancecore-api", "Handoff__ServiceToken", "compliancecore", ["compliancecore"], "launch.redeem"),

        Profile("worker-trainarr-expire", "shared-worker", "TrainArrQualificationExpiration__ServiceToken", "shared-worker", ["trainarr"], "trainarr.qualifications.expire"),
        Profile(
            "worker-trainarr-recertification",
            "shared-worker",
            "TrainArrRecertificationAssignment__ServiceToken",
            "shared-worker",
            ["trainarr"],
            "trainarr.recertification.assign"),
        Profile(
            "worker-trainarr-recalculate",
            "shared-worker",
            "TrainArrQualificationRecalculation__ServiceToken",
            "shared-worker",
            ["trainarr"],
            "trainarr.qualifications.recalculate"),
        Profile(
            "worker-trainarr-rulepack-impact",
            "shared-worker",
            "TrainArrRulePackImpact__ServiceToken",
            "shared-worker",
            ["trainarr"],
            "trainarr.rulepack_impact.scan"),
        Profile(
            "worker-trainarr-evidence-retention",
            "shared-worker",
            "TrainArrEvidenceRetention__ServiceToken",
            "shared-worker",
            ["trainarr"],
            "trainarr.evidence.retention.purge"),
        Profile(
            "worker-trainarr-orphan-references",
            "shared-worker",
            "TrainArrOrphanReference__ServiceToken",
            "shared-worker",
            ["trainarr"],
            "trainarr.orphan_references.scan"),
        Profile(
            "worker-trainarr-staffarr-publish-retry",
            "shared-worker",
            "TrainArrStaffarrPublicationRetry__ServiceToken",
            "shared-worker",
            ["trainarr"],
            "trainarr.staffarr_publications.retry"),
        Profile(
            "worker-trainarr-event-processing",
            "shared-worker",
            "TrainArrEventProcessing__ServiceToken",
            "shared-worker",
            ["trainarr"],
            "trainarr.events.process"),
        Profile(
            "worker-trainarr-notifications",
            "shared-worker",
            "TrainArrNotificationDispatch__ServiceToken",
            "shared-worker",
            ["trainarr"],
            "trainarr.notifications.dispatch"),
        Profile(
            "worker-trainarr-due-reminders",
            "shared-worker",
            "TrainArrAssignmentDueReminders__ServiceToken",
            "shared-worker",
            ["trainarr"],
            "trainarr.assignments.due_reminders.dispatch"),
        Profile(
            "worker-trainarr-assignment-escalation",
            "shared-worker",
            "TrainArrAssignmentEscalation__ServiceToken",
            "shared-worker",
            ["trainarr"],
            "trainarr.assignments.escalate"),
        Profile("worker-staffarr-cert-expire", "shared-worker", "StaffArrCertificationExpiration__ServiceToken", "shared-worker", ["staffarr"], "staffarr.certifications.expire"),
        Profile("worker-staffarr-readiness", "shared-worker", "StaffArrReadinessRollup__ServiceToken", "shared-worker", ["staffarr"], "staffarr.readiness.rollup"),
        Profile("worker-staffarr-permissions", "shared-worker", "StaffArrPermissionProjection__ServiceToken", "shared-worker", ["staffarr"], "staffarr.permissions.project"),
        Profile(
            "worker-staffarr-person-export",
            "shared-worker",
            "StaffArrPersonExportDelivery__ServiceToken",
            "shared-worker",
            ["staffarr"],
            "staffarr.people.export.deliver"),
        Profile(
            "worker-staffarr-personnel-history",
            "shared-worker",
            "StaffArrPersonnelHistoryRollup__ServiceToken",
            "shared-worker",
            ["staffarr"],
            "staffarr.personnel_history.rollup"),
        Profile(
            "worker-staffarr-audit-packages",
            "shared-worker",
            "StaffArrAuditPackageGeneration__ServiceToken",
            "shared-worker",
            ["staffarr"],
            "staffarr.audit_packages.generate"),
        Profile("worker-maintainarr-pm", "shared-worker", "MaintainArrPmDueScan__ServiceToken", "shared-worker", ["maintainarr"], "maintainarr.pm.scan"),
        Profile(
            "worker-maintainarr-notifications",
            "shared-worker",
            "MaintainArrNotificationDispatch__ServiceToken",
            "shared-worker",
            ["maintainarr"],
            "maintainarr.notifications.dispatch"),
        Profile(
            "worker-maintainarr-technician-ref-refresh",
            "shared-worker",
            "MaintainArrTechnicianRefRefresh__ServiceToken",
            "shared-worker",
            ["maintainarr"],
            "maintainarr.technician_refs.refresh"),
        Profile(
            "worker-routarr-notifications",
            "shared-worker",
            "RoutArrNotificationDispatch__ServiceToken",
            "shared-worker",
            ["routarr"],
            "routarr.notifications.dispatch"),
        Profile("worker-supplyarr-reorder", "shared-worker", "SupplyArrReorderEvaluation__ServiceToken", "shared-worker", ["supplyarr"], "supplyarr.reorder.evaluate"),
        Profile(
            "worker-supplyarr-price-snapshot",
            "shared-worker",
            "SupplyArrPriceSnapshot__ServiceToken",
            "shared-worker",
            ["supplyarr"],
            "supplyarr.pricing.snapshots.capture"),
        Profile(
            "worker-supplyarr-lead-time-snapshot",
            "shared-worker",
            "SupplyArrLeadTimeSnapshot__ServiceToken",
            "shared-worker",
            ["supplyarr"],
            "supplyarr.lead_time.snapshots.capture"),
        Profile(
            "worker-supplyarr-availability-snapshot",
            "shared-worker",
            "SupplyArrAvailabilitySnapshot__ServiceToken",
            "shared-worker",
            ["supplyarr"],
            "supplyarr.availability.snapshots.capture"),
        Profile(
            "worker-supplyarr-notifications",
            "shared-worker",
            "SupplyArrNotificationDispatch__ServiceToken",
            "shared-worker",
            ["supplyarr"],
            "supplyarr.notifications.dispatch"),
        Profile(
            "worker-supplyarr-procurement-exception-escalations",
            "shared-worker",
            "SupplyArrProcurementExceptionEscalations__ServiceToken",
            "shared-worker",
            ["supplyarr"],
            "supplyarr.procurement_exceptions.escalate"),
        Profile(
            "worker-compliancecore-scheduled",
            "shared-worker",
            "ComplianceCoreScheduledEvaluation__ServiceToken",
            "shared-worker",
            ["compliancecore"],
            "compliancecore.rules.evaluate.scheduled"),
        Profile(
            "worker-compliancecore-rule-changes",
            "shared-worker",
            "ComplianceCoreRuleChangeMonitor__ServiceToken",
            "shared-worker",
            ["compliancecore"],
            "compliancecore.rule_changes.monitor"),
        Profile(
            "worker-compliancecore-m12-analytics",
            "shared-worker",
            "ComplianceCoreM12AnalyticsBatch__ServiceToken",
            "shared-worker",
            ["compliancecore"],
            "compliancecore.m12_analytics.process_batch"),
        Profile(
            "worker-compliancecore-audit-packages",
            "shared-worker",
            "ComplianceCoreAuditPackageGeneration__ServiceToken",
            "shared-worker",
            ["compliancecore"],
            "compliancecore.audit_packages.generate"),
        Profile(
            "worker-nexarr-companion-notifications",
            "shared-worker",
            "NexArrCompanionNotificationDispatch__ServiceToken",
            "shared-worker",
            ["nexarr"],
            "nexarr.companion.notifications.dispatch"),
        Profile(
            "worker-nexarr-platform-audit-packages",
            "shared-worker",
            "NexArrPlatformAuditPackageGeneration__ServiceToken",
            "shared-worker",
            ["nexarr"],
            "nexarr.platform_audit_packages.generate"),
        Profile(
            "worker-maintainarr-audit-packages",
            "shared-worker",
            "MaintainArrAuditPackageGeneration__ServiceToken",
            "shared-worker",
            ["maintainarr"],
            "maintainarr.audit_packages.generate"),
        Profile(
            "worker-routarr-audit-packages",
            "shared-worker",
            "RoutArrAuditPackageGeneration__ServiceToken",
            "shared-worker",
            ["routarr"],
            "routarr.audit_packages.generate"),
        Profile(
            "worker-trainarr-audit-packages",
            "shared-worker",
            "TrainArrAuditPackageGeneration__ServiceToken",
            "shared-worker",
            ["trainarr"],
            "trainarr.audit_packages.generate"),
        Profile(
            "worker-nexarr-service-token-cleanup",
            "shared-worker",
            "NexArrServiceTokenCleanup__ServiceToken",
            "shared-worker",
            ["nexarr"],
            "nexarr.service_tokens.cleanup.purge"),
        Profile(
            "worker-nexarr-entitlement-reconciliation",
            "shared-worker",
            "NexArrEntitlementReconciliation__ServiceToken",
            "shared-worker",
            ["nexarr"],
            "nexarr.entitlements.reconcile"),
        Profile(
            "worker-nexarr-tenant-lifecycle",
            "shared-worker",
            "NexArrTenantLifecycle__ServiceToken",
            "shared-worker",
            ["nexarr"],
            "nexarr.tenants.lifecycle.process"),
        Profile(
            "worker-maintainarr-defect-escalation",
            "shared-worker",
            "MaintainArrDefectEscalation__ServiceToken",
            "shared-worker",
            ["maintainarr"],
            "maintainarr.defects.escalate"),
        Profile(
            "worker-maintainarr-asset-status-rollup",
            "shared-worker",
            "MaintainArrAssetStatusRollup__ServiceToken",
            "shared-worker",
            ["maintainarr"],
            "maintainarr.asset_status.rollup"),
        Profile(
            "worker-maintainarr-maintenance-history-rollup",
            "shared-worker",
            "MaintainArrMaintenanceHistoryRollup__ServiceToken",
            "shared-worker",
            ["maintainarr"],
            "maintainarr.maintenance_history.rollup"),
        Profile(
            "worker-routarr-trip-completion-rollup",
            "shared-worker",
            "RoutArrTripCompletionRollup__ServiceToken",
            "shared-worker",
            ["routarr"],
            "routarr.trips.completion.rollup"),
        Profile(
            "worker-routarr-attachment-retention",
            "shared-worker",
            "RoutArrAttachmentRetention__ServiceToken",
            "shared-worker",
            ["routarr"],
            "routarr.attachments.retention.purge"),
        Profile(
            "worker-supplyarr-procurement-coordination",
            "shared-worker",
            "SupplyArrProcurementCoordination__ServiceToken",
            "shared-worker",
            ["supplyarr"],
            "supplyarr.procurement.coordination"),
        Profile(
            "worker-supplyarr-approval-reminders",
            "shared-worker",
            "SupplyArrApprovalReminders__ServiceToken",
            "shared-worker",
            ["supplyarr"],
            "supplyarr.approval_reminders.dispatch"),
        Profile(
            "worker-supplyarr-demand-processing",
            "shared-worker",
            "SupplyArrDemandProcessing__ServiceToken",
            "shared-worker",
            ["supplyarr"],
            "supplyarr.demand.process"),
        Profile(
            "worker-supplyarr-integration-events",
            "shared-worker",
            "SupplyArrIntegrationEvents__ServiceToken",
            "shared-worker",
            ["supplyarr"],
            "supplyarr.integration.events.process"),
    ];

    public static IReadOnlyList<StlIntegrationTokenProfile> ForConsumer(string consumerService) =>
        All.Where(p => string.Equals(p.ConsumerService, consumerService, StringComparison.OrdinalIgnoreCase)).ToList();

    private static StlIntegrationTokenProfile Profile(
        string profileKey,
        string consumerService,
        string configurationKey,
        string sourceProductKey,
        IReadOnlyList<string> allowedProductKeys,
        string actionScope) =>
        new(profileKey, consumerService, configurationKey, sourceProductKey, allowedProductKeys, actionScope);
}
