// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SupplyArr.Api.Data;

#nullable disable

namespace SupplyArr.Api.Migrations
{
    [DbContext(typeof(SupplyArrDbContext))]
    [Migration("20260527175402_SupplyArrMaintainArrDemandStatusCallbacks")]
    partial class SupplyArrMaintainArrDemandStatusCallbacks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("STLCompliance.Shared.Data.PlatformMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("platform_metadata", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.Backorder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackorderKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpectedBy")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FulfilledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FulfilledByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderLineId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PurchaseRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PurchaseRequestLineId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityBackordered")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("QuantityFulfilled")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("ReceivingReceiptId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReceivingReceiptLineId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("PurchaseOrderLineId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "BackorderKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "PurchaseOrderId");

                    b.HasIndex("TenantId", "PartId", "Status");

                    b.HasIndex("TenantId", "PurchaseOrderLineId", "Status");

                    b.ToTable("supplyarr_backorders", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.ExternalParty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("PartyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TaxIdentifier")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ApprovalStatus");

                    b.HasIndex("TenantId", "PartyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "PartyType", "Status");

                    b.ToTable("supplyarr_external_parties", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.InventoryBin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BinKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InventoryLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InventoryLocationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "InventoryLocationId");

                    b.HasIndex("TenantId", "InventoryLocationId", "BinKey")
                        .IsUnique();

                    b.ToTable("supplyarr_inventory_bins", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.InventoryLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "LocationKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "LocationType", "Status");

                    b.ToTable("supplyarr_inventory_locations", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.MaintainArrDemandRef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastStatusCallbackAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MaintainarrAssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaintainarrPublicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaintainarrWorkOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaintainarrWorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ProcurementStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PurchaseRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseRequestId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "MaintainarrPublicationId")
                        .IsUnique();

                    b.HasIndex("TenantId", "MaintainarrWorkOrderId");

                    b.HasIndex("TenantId", "PurchaseOrderId");

                    b.HasIndex("TenantId", "PurchaseRequestId");

                    b.HasIndex("TenantId", "Status", "ReceivedAt");

                    b.ToTable("supplyarr_maintainarr_demand_refs", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.MaintainArrDemandRefLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DemandRefId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("MaintainarrDemandLineId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("PartId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("QuantityRequested")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("DemandRefId");

                    b.HasIndex("PartId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "MaintainarrDemandLineId");

                    b.HasIndex("TenantId", "DemandRefId", "LineNumber");

                    b.ToTable("supplyarr_maintainarr_demand_ref_lines", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ManufacturerPartNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("PartCatalogId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("ReorderPoint")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("ReorderQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartCatalogId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PartCatalogId");

                    b.HasIndex("TenantId", "PartKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "CategoryKey", "Status");

                    b.ToTable("supplyarr_parts", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CatalogKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CatalogKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("supplyarr_part_catalogs", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartManufacturerAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AliasKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ManufacturerPartNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PartId");

                    b.HasIndex("TenantId", "PartId", "AliasKey")
                        .IsUnique();

                    b.ToTable("supplyarr_part_manufacturer_aliases", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartStockLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InventoryBinId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityOnHand")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("QuantityReserved")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InventoryBinId");

                    b.HasIndex("PartId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "InventoryBinId");

                    b.HasIndex("TenantId", "PartId");

                    b.HasIndex("TenantId", "PartId", "InventoryBinId")
                        .IsUnique();

                    b.ToTable("supplyarr_part_stock_levels", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartVendorAvailabilitySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("PartVendorLinkId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("QuantityAvailable")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("SnapshotKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartVendorLinkId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "SnapshotKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "PartVendorLinkId", "EffectiveFrom");

                    b.HasIndex("TenantId", "PartVendorLinkId", "EffectiveTo")
                        .HasDatabaseName("IX_supplyarr_part_vendor_availability_snapshots_TenantId_Part~1");

                    b.ToTable("supplyarr_part_vendor_availability_snapshots", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartVendorLeadTimeSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("PartVendorLinkId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartVendorLinkId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "SnapshotKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "PartVendorLinkId", "EffectiveFrom");

                    b.HasIndex("TenantId", "PartVendorLinkId", "EffectiveTo")
                        .HasDatabaseName("IX_supplyarr_part_vendor_lead_time_snapshots_TenantId_PartVen~1");

                    b.ToTable("supplyarr_part_vendor_lead_time_snapshots", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartVendorLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExternalPartyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VendorPartNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalPartyId");

                    b.HasIndex("PartId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PartId");

                    b.HasIndex("TenantId", "PartId", "ExternalPartyId")
                        .IsUnique();

                    b.ToTable("supplyarr_part_vendor_links", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartVendorPricingSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MinimumOrderQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("PartVendorLinkId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartVendorLinkId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "SnapshotKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "PartVendorLinkId", "EffectiveFrom");

                    b.HasIndex("TenantId", "PartVendorLinkId", "EffectiveTo")
                        .HasDatabaseName("IX_supplyarr_part_vendor_pricing_snapshots_TenantId_PartVendo~1");

                    b.ToTable("supplyarr_part_vendor_pricing_snapshots", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ExternalPartyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RoleLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalPartyId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ExternalPartyId");

                    b.ToTable("supplyarr_party_contacts", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IssuedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("OrderKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorPartyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseRequestId");

                    b.HasIndex("TenantId");

                    b.HasIndex("VendorPartyId");

                    b.HasIndex("TenantId", "OrderKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "PurchaseRequestId");

                    b.HasIndex("TenantId", "Status", "UpdatedAt");

                    b.ToTable("supplyarr_purchase_orders", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PurchaseOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PurchaseRequestLineId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityOrdered")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("QuantityReceived")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("PurchaseRequestLineId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PurchaseOrderId");

                    b.HasIndex("TenantId", "PurchaseOrderId", "LineNumber")
                        .IsUnique();

                    b.ToTable("supplyarr_purchase_order_lines", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PurchaseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RequestKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorPartyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("VendorPartyId");

                    b.HasIndex("TenantId", "RequestKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status", "UpdatedAt");

                    b.ToTable("supplyarr_purchase_requests", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PurchaseRequestLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityRequested")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("PurchaseRequestId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PurchaseRequestId");

                    b.HasIndex("TenantId", "PurchaseRequestId", "LineNumber")
                        .IsUnique();

                    b.ToTable("supplyarr_purchase_request_lines", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.ReceivingException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("ReceivingReceiptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceivingReceiptLineId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceivingReceiptId");

                    b.HasIndex("ReceivingReceiptLineId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ReceivingReceiptId");

                    b.HasIndex("TenantId", "ReceivingReceiptLineId");

                    b.HasIndex("TenantId", "ReceivingReceiptLineId", "ExceptionType", "Status")
                        .HasDatabaseName("IX_supplyarr_receiving_exceptions_TenantId_ReceivingReceiptLi~1");

                    b.ToTable("supplyarr_receiving_exceptions", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.ReceivingReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryBinId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PostedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReceiptKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InventoryBinId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "PurchaseOrderId");

                    b.HasIndex("TenantId", "ReceiptKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status", "UpdatedAt");

                    b.ToTable("supplyarr_receiving_receipts", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.ReceivingReceiptLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderLineId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityExpected")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("QuantityReceived")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("ReceivingReceiptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("PurchaseOrderLineId");

                    b.HasIndex("ReceivingReceiptId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ReceivingReceiptId");

                    b.HasIndex("TenantId", "ReceivingReceiptId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_supplyarr_receiving_receipt_lines_TenantId_ReceivingReceip~1");

                    b.ToTable("supplyarr_receiving_receipt_lines", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.SupplyArrAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.ToTable("supplyarr_audit_events", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.VendorReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InventoryBinId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PostedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReturnKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RmaNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorPartyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventoryBinId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("TenantId");

                    b.HasIndex("VendorPartyId");

                    b.HasIndex("TenantId", "PurchaseOrderId");

                    b.HasIndex("TenantId", "ReturnKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "VendorPartyId");

                    b.HasIndex("TenantId", "Status", "UpdatedAt");

                    b.ToTable("supplyarr_vendor_returns", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.VendorReturnLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PurchaseOrderLineId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorReturnId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("PurchaseOrderLineId");

                    b.HasIndex("TenantId");

                    b.HasIndex("VendorReturnId");

                    b.HasIndex("TenantId", "PartId");

                    b.HasIndex("TenantId", "VendorReturnId");

                    b.HasIndex("TenantId", "VendorReturnId", "LineNumber")
                        .IsUnique();

                    b.ToTable("supplyarr_vendor_return_lines", (string)null);
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.Backorder", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupplyArr.Api.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupplyArr.Api.Entities.PurchaseOrderLine", "PurchaseOrderLine")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("PurchaseOrderLine");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.InventoryBin", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.InventoryLocation", "InventoryLocation")
                        .WithMany("Bins")
                        .HasForeignKey("InventoryLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryLocation");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.MaintainArrDemandRef", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.PurchaseRequest", "PurchaseRequest")
                        .WithMany()
                        .HasForeignKey("PurchaseRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PurchaseRequest");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.MaintainArrDemandRefLine", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.MaintainArrDemandRef", "DemandRef")
                        .WithMany("Lines")
                        .HasForeignKey("DemandRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupplyArr.Api.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DemandRef");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.Part", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.PartCatalog", "PartCatalog")
                        .WithMany("Parts")
                        .HasForeignKey("PartCatalogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PartCatalog");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartManufacturerAlias", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.Part", "Part")
                        .WithMany("ManufacturerAliases")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartStockLevel", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.InventoryBin", "InventoryBin")
                        .WithMany("StockLevels")
                        .HasForeignKey("InventoryBinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupplyArr.Api.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryBin");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartVendorAvailabilitySnapshot", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.PartVendorLink", "PartVendorLink")
                        .WithMany()
                        .HasForeignKey("PartVendorLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartVendorLink");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartVendorLeadTimeSnapshot", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.PartVendorLink", "PartVendorLink")
                        .WithMany()
                        .HasForeignKey("PartVendorLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartVendorLink");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartVendorLink", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.ExternalParty", "ExternalParty")
                        .WithMany()
                        .HasForeignKey("ExternalPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupplyArr.Api.Entities.Part", "Part")
                        .WithMany("VendorLinks")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalParty");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartVendorPricingSnapshot", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.PartVendorLink", "PartVendorLink")
                        .WithMany()
                        .HasForeignKey("PartVendorLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartVendorLink");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartyContact", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.ExternalParty", "ExternalParty")
                        .WithMany("Contacts")
                        .HasForeignKey("ExternalPartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalParty");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.PurchaseRequest", "PurchaseRequest")
                        .WithMany()
                        .HasForeignKey("PurchaseRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupplyArr.Api.Entities.ExternalParty", "VendorParty")
                        .WithMany()
                        .HasForeignKey("VendorPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseRequest");

                    b.Navigation("VendorParty");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PurchaseOrderLine", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupplyArr.Api.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupplyArr.Api.Entities.PurchaseRequestLine", "PurchaseRequestLine")
                        .WithMany()
                        .HasForeignKey("PurchaseRequestLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Part");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("PurchaseRequestLine");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PurchaseRequest", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.ExternalParty", "VendorParty")
                        .WithMany()
                        .HasForeignKey("VendorPartyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VendorParty");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PurchaseRequestLine", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupplyArr.Api.Entities.PurchaseRequest", "PurchaseRequest")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("PurchaseRequest");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.ReceivingException", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.ReceivingReceipt", "ReceivingReceipt")
                        .WithMany()
                        .HasForeignKey("ReceivingReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupplyArr.Api.Entities.ReceivingReceiptLine", "ReceivingReceiptLine")
                        .WithMany("Exceptions")
                        .HasForeignKey("ReceivingReceiptLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceivingReceipt");

                    b.Navigation("ReceivingReceiptLine");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.ReceivingReceipt", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.InventoryBin", "InventoryBin")
                        .WithMany()
                        .HasForeignKey("InventoryBinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupplyArr.Api.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryBin");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.ReceivingReceiptLine", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupplyArr.Api.Entities.PurchaseOrderLine", "PurchaseOrderLine")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupplyArr.Api.Entities.ReceivingReceipt", "ReceivingReceipt")
                        .WithMany("Lines")
                        .HasForeignKey("ReceivingReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("PurchaseOrderLine");

                    b.Navigation("ReceivingReceipt");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.VendorReturn", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.InventoryBin", "InventoryBin")
                        .WithMany()
                        .HasForeignKey("InventoryBinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupplyArr.Api.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SupplyArr.Api.Entities.ExternalParty", "VendorParty")
                        .WithMany()
                        .HasForeignKey("VendorPartyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryBin");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("VendorParty");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.VendorReturnLine", b =>
                {
                    b.HasOne("SupplyArr.Api.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupplyArr.Api.Entities.PurchaseOrderLine", "PurchaseOrderLine")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SupplyArr.Api.Entities.VendorReturn", "VendorReturn")
                        .WithMany("Lines")
                        .HasForeignKey("VendorReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("PurchaseOrderLine");

                    b.Navigation("VendorReturn");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.ExternalParty", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.InventoryBin", b =>
                {
                    b.Navigation("StockLevels");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.InventoryLocation", b =>
                {
                    b.Navigation("Bins");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.MaintainArrDemandRef", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.Part", b =>
                {
                    b.Navigation("ManufacturerAliases");

                    b.Navigation("VendorLinks");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PartCatalog", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.PurchaseRequest", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.ReceivingReceipt", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.ReceivingReceiptLine", b =>
                {
                    b.Navigation("Exceptions");
                });

            modelBuilder.Entity("SupplyArr.Api.Entities.VendorReturn", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
