namespace SupplyArr.Api.Contracts;

public sealed record SupplyContractResponse(
    Guid ContractId,
    string ContractKey,
    string ContractType,
    string Title,
    Guid SupplierId,
    string SupplierKey,
    string SupplierDisplayName,
    Guid? ParentSupplierId,
    string? ParentSupplierDisplayName,
    string SupplierUnitKind,
    IReadOnlyList<string> SupplierServiceTypes,
    DateTimeOffset EffectiveAt,
    DateTimeOffset? ExpiresAt,
    DateTimeOffset? RenewalAt,
    string PaymentTerms,
    string FreightTerms,
    string WarrantyTerms,
    decimal? MinimumSpend,
    string ServiceLevelAgreement,
    string ApprovalStatus,
    string Status,
    string Notes,
    Guid CreatedByUserId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record CreateSupplyContractRequest(
    string ContractKey,
    string ContractType,
    string Title,
    Guid? SupplierId,
    DateTimeOffset? EffectiveAt,
    DateTimeOffset? ExpiresAt,
    DateTimeOffset? RenewalAt,
    string PaymentTerms,
    string FreightTerms,
    string WarrantyTerms,
    decimal? MinimumSpend,
    string ServiceLevelAgreement,
    string ApprovalStatus,
    string Status,
    string Notes);
