namespace StaffArr.Api.Contracts;

public sealed record CreatePersonnelIncidentRequest(
    Guid PersonId,
    string ReasonCategoryKey,
    string Severity,
    string Title,
    string Description,
    DateTimeOffset OccurredAt,
    string? Status = null,
    string? IncidentSource = null,
    string? IncidentType = null,
    DateTimeOffset? DiscoveredAt = null,
    Guid? SiteOrgUnitId = null,
    Guid? DepartmentOrgUnitId = null,
    string? LocationDetail = null,
    Guid? ReporterPersonId = null,
    Guid? ManagerPersonId = null,
    IReadOnlyList<Guid>? WitnessPersonIds = null,
    IReadOnlyList<Guid>? AdditionalInvolvedPersonIds = null,
    bool EmployeeSelfReport = false,
    string? ImmediateActionsTaken = null,
    string? RootCause = null,
    IReadOnlyList<string>? CategoryKeys = null,
    string? ReadinessDecision = null,
    string? WorkRestriction = null,
    string? ReturnToWorkNeeded = null,
    string? PpeConcern = null,
    string? MedicalAttention = null,
    string? OutOfServiceRemoveFromDuty = null,
    string? FollowUpRequired = null,
    bool TrainingReviewRequired = false,
    string? TrainingReviewReason = null,
    string? RelatedAssetReference = null,
    string? RelatedWorkOrderReference = null,
    string? RelatedRouteReference = null,
    string? RelatedSupplierReference = null,
    string? RelatedDocumentReference = null,
    string? RelatedPolicyReference = null,
    bool EvidencePackageRequested = false,
    bool NotifyManager = true,
    bool NotifySafetyCompliance = true,
    bool NotifyHr = false,
    bool CreateFollowUpTask = false,
    DateTimeOffset? FollowUpDueAt = null);

public sealed record SubmitSelfReportedPersonnelIncidentRequest(
    string ReasonCategoryKey,
    string Severity,
    string Title,
    string Description,
    DateTimeOffset OccurredAt);

public sealed record IngestProductIncidentRequest(
    Guid TenantId,
    string SourceProduct,
    Guid SourceIncidentId,
    string? SourceEventKind,
    Guid PersonId,
    string ReasonCategoryKey,
    string Severity,
    string Title,
    string Description,
    DateTimeOffset OccurredAt,
    string? SourceReferenceKey = null);

public sealed record IngestProductIncidentResponse(
    Guid IncidentId,
    Guid PersonId,
    string SourceProduct,
    Guid SourceIncidentId,
    string Status,
    bool IdempotentReplay,
    ProductSourceReferenceSnapshotResponse? SourceSnapshot = null);

public sealed record ProductSourceReferenceSnapshotResponse(
    string SourceProduct,
    string SourceEntity,
    string SourceId,
    string LabelSnapshot,
    string StatusSnapshot,
    DateTimeOffset SelectedAt,
    DateTimeOffset LastVerifiedAt,
    DateTimeOffset? LastSyncedAt,
    bool IsAuthoritative = false);

public sealed record IncidentTrainarrRoutingResponse(
    string RoutingStatus,
    Guid TrainarrRemediationId,
    DateTimeOffset RoutedAt,
    Guid RoutedByUserId,
    IncidentTrainarrRemediationResultResponse? RemediationResult = null);

public sealed record IncidentTrainarrRemediationResultResponse(
    Guid RemediationId,
    string Status,
    string ReasonCategoryKey,
    string Severity,
    string Title,
    DateTimeOffset CreatedAt);

public sealed record PersonnelIncidentSummaryResponse(
    Guid IncidentId,
    Guid PersonId,
    string ReasonCategoryKey,
    string Severity,
    string Status,
    string Title,
    DateTimeOffset OccurredAt,
    DateTimeOffset ReportedAt,
    Guid ReportedByUserId,
    IncidentTrainarrRoutingResponse? TrainarrRouting,
    string? IncidentSource = null,
    string? IncidentType = null,
    DateTimeOffset? DiscoveredAt = null,
    Guid? ReporterPersonId = null,
    Guid? ManagerPersonId = null,
    IReadOnlyList<string>? CategoryKeys = null,
    string? ReadinessDecision = null,
    bool TrainingReviewRequired = false,
    string? SourceProduct = null,
    Guid? SourceIncidentId = null,
    string? SourceEventKind = null,
    string? SourceReferenceKey = null,
    ProductSourceReferenceSnapshotResponse? SourceSnapshot = null);

public sealed record PersonnelIncidentDetailResponse(
    Guid IncidentId,
    Guid PersonId,
    string ReasonCategoryKey,
    string Severity,
    string Status,
    string Title,
    string Description,
    DateTimeOffset OccurredAt,
    DateTimeOffset ReportedAt,
    Guid ReportedByUserId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    IncidentTrainarrRoutingResponse? TrainarrRouting,
    string? IncidentSource = null,
    string? IncidentType = null,
    DateTimeOffset? DiscoveredAt = null,
    Guid? SiteOrgUnitId = null,
    Guid? DepartmentOrgUnitId = null,
    string? LocationDetail = null,
    Guid? ReporterPersonId = null,
    Guid? ManagerPersonId = null,
    IReadOnlyList<Guid>? WitnessPersonIds = null,
    IReadOnlyList<Guid>? AdditionalInvolvedPersonIds = null,
    bool EmployeeSelfReport = false,
    string? ImmediateActionsTaken = null,
    string? RootCause = null,
    IReadOnlyList<string>? CategoryKeys = null,
    string? ReadinessDecision = null,
    string? WorkRestriction = null,
    string? ReturnToWorkNeeded = null,
    string? PpeConcern = null,
    string? MedicalAttention = null,
    string? OutOfServiceRemoveFromDuty = null,
    string? FollowUpRequired = null,
    bool TrainingReviewRequired = false,
    string? TrainingReviewReason = null,
    string? RelatedAssetReference = null,
    string? RelatedWorkOrderReference = null,
    string? RelatedRouteReference = null,
    string? RelatedSupplierReference = null,
    string? RelatedDocumentReference = null,
    string? RelatedPolicyReference = null,
    bool EvidencePackageRequested = false,
    bool NotifyManager = false,
    bool NotifySafetyCompliance = false,
    bool NotifyHr = false,
    bool CreateFollowUpTask = false,
    DateTimeOffset? FollowUpDueAt = null,
    string? SourceProduct = null,
    Guid? SourceIncidentId = null,
    string? SourceEventKind = null,
    string? SourceReferenceKey = null,
    ProductSourceReferenceSnapshotResponse? SourceSnapshot = null);

public sealed record RouteIncidentToTrainarrResponse(
    Guid IncidentId,
    Guid PersonId,
    string ReasonCategoryKey,
    string Status,
    IncidentTrainarrRoutingResponse TrainarrRouting);
