namespace StaffArr.Api.Contracts;

public sealed record PerformanceReviewCycleResponse(
    Guid Id,
    Guid PersonId,
    string CycleName,
    string CycleType,
    string Status,
    DateOnly StartDate,
    DateOnly EndDate,
    DateOnly? SelfReviewDueDate,
    DateOnly? ManagerReviewDueDate,
    Guid? ManagerPersonId,
    DateTimeOffset? SelfReviewCompletedAt,
    DateTimeOffset? ManagerReviewCompletedAt,
    string? OverallRating,
    bool PromotionReady,
    bool SuccessionReady,
    DateTimeOffset? NextCheckInAt,
    string? Summary,
    string? DevelopmentPlan,
    string? SourceProductKey,
    string? SourceRef,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record UpsertPerformanceReviewCycleRequest(
    Guid PersonId,
    string CycleName,
    string CycleType,
    string Status,
    DateOnly StartDate,
    DateOnly EndDate,
    DateOnly? SelfReviewDueDate,
    DateOnly? ManagerReviewDueDate,
    Guid? ManagerPersonId,
    DateTimeOffset? SelfReviewCompletedAt,
    DateTimeOffset? ManagerReviewCompletedAt,
    string? OverallRating,
    bool PromotionReady,
    bool SuccessionReady,
    DateTimeOffset? NextCheckInAt,
    string? Summary,
    string? DevelopmentPlan,
    string? SourceProductKey,
    string? SourceRef);

public sealed record PerformanceGoalResponse(
    Guid Id,
    Guid PersonId,
    Guid? PerformanceReviewCycleId,
    string GoalTitle,
    string GoalType,
    string Status,
    string Priority,
    decimal ProgressPercent,
    DateOnly StartDate,
    DateOnly? TargetDate,
    DateTimeOffset? CompletedAt,
    Guid? OwnerPersonId,
    string? SuccessMetric,
    string? Summary,
    string? ResultSummary,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record UpsertPerformanceGoalRequest(
    Guid PersonId,
    Guid? PerformanceReviewCycleId,
    string GoalTitle,
    string GoalType,
    string Status,
    string Priority,
    decimal ProgressPercent,
    DateOnly StartDate,
    DateOnly? TargetDate,
    DateTimeOffset? CompletedAt,
    Guid? OwnerPersonId,
    string? SuccessMetric,
    string? Summary,
    string? ResultSummary);

public sealed record PerformanceCompetencyAssessmentResponse(
    Guid Id,
    Guid PersonId,
    Guid? PerformanceReviewCycleId,
    string CompetencyKey,
    string CompetencyName,
    string ExpectedLevel,
    string CurrentLevel,
    string Rating,
    string Status,
    string? Notes,
    Guid? AssessedByPersonId,
    DateTimeOffset? AssessedAt,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record UpsertPerformanceCompetencyAssessmentRequest(
    Guid PersonId,
    Guid? PerformanceReviewCycleId,
    string CompetencyKey,
    string CompetencyName,
    string ExpectedLevel,
    string CurrentLevel,
    string Rating,
    string Status,
    string? Notes,
    Guid? AssessedByPersonId,
    DateTimeOffset? AssessedAt);

public sealed record PerformanceFeedbackEntryResponse(
    Guid Id,
    Guid PersonId,
    Guid? PerformanceReviewCycleId,
    string FeedbackType,
    string Visibility,
    string Subject,
    string Body,
    string? Sentiment,
    Guid? AuthorPersonId,
    Guid? RelatedPersonId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record CreatePerformanceFeedbackEntryRequest(
    Guid PersonId,
    Guid? PerformanceReviewCycleId,
    string FeedbackType,
    string Visibility,
    string Subject,
    string Body,
    string? Sentiment,
    Guid? AuthorPersonId,
    Guid? RelatedPersonId);

public sealed record PerformanceImprovementPlanResponse(
    Guid Id,
    Guid PersonId,
    string PlanName,
    string Status,
    DateOnly StartDate,
    DateOnly? TargetDate,
    string? CheckInCadence,
    DateTimeOffset? NextCheckInAt,
    Guid? ManagerPersonId,
    Guid? HrOwnerPersonId,
    string? Summary,
    string? Expectations,
    string? SuccessCriteria,
    string? SourceProductKey,
    string? SourceRef,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record UpsertPerformanceImprovementPlanRequest(
    Guid PersonId,
    string PlanName,
    string Status,
    DateOnly StartDate,
    DateOnly? TargetDate,
    string? CheckInCadence,
    DateTimeOffset? NextCheckInAt,
    Guid? ManagerPersonId,
    Guid? HrOwnerPersonId,
    string? Summary,
    string? Expectations,
    string? SuccessCriteria,
    string? SourceProductKey,
    string? SourceRef);
