namespace StaffArr.Api.Contracts;

public sealed record RecruitingRequisitionResponse(
    Guid Id,
    string RequisitionNumber,
    string Title,
    string JobCode,
    string JobFamily,
    string? DepartmentRef,
    string? SiteRef,
    string? LocationRef,
    Guid? HiringManagerPersonId,
    Guid? RecruiterPersonId,
    string Status,
    int HeadcountRequested,
    int FilledCount,
    DateOnly? OpenDate,
    DateOnly? TargetStartDate,
    string? SourceProductKey,
    string? SourceRef,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record UpsertRecruitingRequisitionRequest(
    string RequisitionNumber,
    string Title,
    string JobCode,
    string JobFamily,
    string? DepartmentRef,
    string? SiteRef,
    string? LocationRef,
    Guid? HiringManagerPersonId,
    Guid? RecruiterPersonId,
    string Status,
    int HeadcountRequested,
    int FilledCount,
    DateOnly? OpenDate,
    DateOnly? TargetStartDate,
    string? SourceProductKey,
    string? SourceRef);

public sealed record RecruitingCandidateResponse(
    Guid Id,
    Guid? RecruitingRequisitionId,
    Guid? EmploymentApplicationSubmissionId,
    Guid? PersonId,
    string CandidateName,
    string CandidateEmail,
    string? CandidatePhone,
    string SourceType,
    string Stage,
    string Status,
    string? BackgroundCheckStatus,
    string? DrugScreenStatus,
    string? PhysicalStatus,
    string? OfferStatus,
    decimal? Score,
    string? Notes,
    string? SourceProductKey,
    string? SourceRef,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record UpsertRecruitingCandidateRequest(
    Guid? RecruitingRequisitionId,
    Guid? EmploymentApplicationSubmissionId,
    Guid? PersonId,
    string CandidateName,
    string CandidateEmail,
    string? CandidatePhone,
    string SourceType,
    string Stage,
    string Status,
    string? BackgroundCheckStatus,
    string? DrugScreenStatus,
    string? PhysicalStatus,
    string? OfferStatus,
    decimal? Score,
    string? Notes,
    string? SourceProductKey,
    string? SourceRef);

public sealed record RecruitingInterviewStageResponse(
    Guid Id,
    Guid RecruitingCandidateId,
    string StageName,
    string Status,
    DateTimeOffset? ScheduledAt,
    DateTimeOffset? CompletedAt,
    Guid? InterviewerPersonId,
    decimal? Score,
    string? Recommendation,
    string? Notes,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record UpsertRecruitingInterviewStageRequest(
    Guid RecruitingCandidateId,
    string StageName,
    string Status,
    DateTimeOffset? ScheduledAt,
    DateTimeOffset? CompletedAt,
    Guid? InterviewerPersonId,
    decimal? Score,
    string? Recommendation,
    string? Notes);

public sealed record RecruitingOfferResponse(
    Guid Id,
    Guid RecruitingCandidateId,
    string Status,
    string Title,
    string PayBasis,
    decimal? AnnualSalary,
    decimal? HourlyRate,
    DateOnly? StartDate,
    DateTimeOffset? ApprovedAt,
    Guid? ApprovedByPersonId,
    DateTimeOffset? AcceptedAt,
    DateTimeOffset? DeclinedAt,
    string? Notes,
    string? SourceProductKey,
    string? SourceRef,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

public sealed record UpsertRecruitingOfferRequest(
    Guid RecruitingCandidateId,
    string Status,
    string Title,
    string PayBasis,
    decimal? AnnualSalary,
    decimal? HourlyRate,
    DateOnly? StartDate,
    DateTimeOffset? ApprovedAt,
    Guid? ApprovedByPersonId,
    DateTimeOffset? AcceptedAt,
    DateTimeOffset? DeclinedAt,
    string? Notes,
    string? SourceProductKey,
    string? SourceRef);

