using STLCompliance.Shared.Hosting;
using STLCompliance.Shared.Print;

namespace ReportArr.Api.Services;

public sealed class ReportArrPrintTemplateCatalog(ProductDescriptor product) : IPrintTemplateCatalog
{
    private readonly StlDefaultPrintTemplateCatalog _defaultCatalog = new(product);

    public IReadOnlyList<StlPrintTemplateDescriptor> ListTemplates() =>
    [
        .. _defaultCatalog.ListTemplates(),
        BuildTemplate(
            "reportarr.report.print",
            "Report print view",
            "Browser-printable ReportArr report run preview.",
            StlPrintFormats.HtmlPrint,
            StlPrintDocumentStatuses.WorkingCopy,
            requiresArchive: false,
            requiresOfficialIssue: false,
            requiresReprintReason: false),
        BuildTemplate(
            "reportarr.report.pdf_export",
            "Report PDF export",
            "Server-generated PDF export for a ReportArr report run.",
            StlPrintFormats.Pdf,
            StlPrintDocumentStatuses.Copy,
            requiresArchive: false,
            requiresOfficialIssue: false,
            requiresReprintReason: false),
        BuildTemplate(
            "reportarr.dashboard.snapshot",
            "Dashboard snapshot",
            "Printable dashboard snapshot for ReportArr-owned dashboards.",
            StlPrintFormats.Pdf,
            StlPrintDocumentStatuses.WorkingCopy,
            requiresArchive: false,
            requiresOfficialIssue: false,
            requiresReprintReason: false),
        BuildTemplate(
            "reportarr.scheduled_report.output",
            "Scheduled report output",
            "Server-generated PDF output for a scheduled ReportArr report.",
            StlPrintFormats.Pdf,
            StlPrintDocumentStatuses.Copy,
            requiresArchive: false,
            requiresOfficialIssue: false,
            requiresReprintReason: false),
        BuildTemplate(
            "reportarr.audit.packet",
            "Audit packet",
            "Official cross-product audit packet assembled by ReportArr.",
            StlPrintFormats.PacketPdf,
            StlPrintDocumentStatuses.Official,
            requiresArchive: true,
            requiresOfficialIssue: true,
            requiresReprintReason: true),
        BuildTemplate(
            "reportarr.compliance_readiness.packet",
            "Compliance readiness packet",
            "Compliance readiness packet generated by ReportArr.",
            StlPrintFormats.PacketPdf,
            StlPrintDocumentStatuses.Copy,
            requiresArchive: false,
            requiresOfficialIssue: false,
            requiresReprintReason: false),
        BuildTemplate(
            "reportarr.management.summary",
            "Management summary",
            "Executive management summary generated from a ReportArr audit package.",
            StlPrintFormats.Pdf,
            StlPrintDocumentStatuses.Copy,
            requiresArchive: false,
            requiresOfficialIssue: false,
            requiresReprintReason: false),
    ];

    public StlPrintTemplateDescriptor? GetTemplate(string templateKey) =>
        ListTemplates().FirstOrDefault(template =>
            string.Equals(template.TemplateKey, templateKey, StringComparison.OrdinalIgnoreCase));

    private static StlPrintTemplateDescriptor BuildTemplate(
        string templateKey,
        string name,
        string description,
        string format,
        string documentStatus,
        bool requiresArchive,
        bool requiresOfficialIssue,
        bool requiresReprintReason)
    {
        var fileStem = templateKey.Replace('.', '-');
        return new StlPrintTemplateDescriptor(
            TemplateKey: templateKey,
            ProductKey: "reportarr",
            Name: name,
            Description: description,
            Version: "1",
            DataContractVersion: "1",
            Format: format,
            PaperSize: "letter",
            Orientation: "portrait",
            DocumentStatus: documentStatus,
            IsSystemTemplate: true,
            TenantOverrideAllowed: false,
            RequiresArchive: requiresArchive,
            RequiresOfficialIssue: requiresOfficialIssue,
            RequiresReprintReason: requiresReprintReason,
            RetentionClass: requiresArchive || requiresOfficialIssue ? "official_output" : "working_output",
            DefaultFileNamePattern: $"{fileStem}-{{sourceDisplayRef}}");
    }
}
