import { useId, useState, type ReactNode } from 'react'
import type { PrintDocumentStatus } from './types'

function formatDateTime(value: string | null | undefined) {
  if (!value) {
    return 'Not set'
  }

  const parsed = new Date(value)
  if (Number.isNaN(parsed.getTime())) {
    return value
  }

  return parsed.toLocaleString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    timeZoneName: 'short',
  })
}

function formatDocumentStatus(value: PrintDocumentStatus) {
  switch (value) {
    case 'draft':
      return 'Draft'
    case 'working_copy':
      return 'Working copy'
    case 'official':
      return 'Official'
    case 'copy':
      return 'Copy'
    case 'redacted':
      return 'Redacted'
    default:
      return value
  }
}

function documentStatusClasses(status: PrintDocumentStatus) {
  switch (status) {
    case 'official':
      return 'border-[var(--color-success-border)] bg-[var(--color-success-bg)] text-[var(--color-success-text)]'
    case 'copy':
      return 'border-[var(--color-info-border)] bg-[var(--color-info-bg)] text-[var(--color-info-text)]'
    case 'redacted':
      return 'border-[var(--color-warning-border)] bg-[var(--color-warning-bg)] text-[var(--color-warning-text)]'
    case 'draft':
      return 'border-[var(--color-neutral-badge-border)] bg-[var(--color-neutral-badge-bg)] text-[var(--color-neutral-badge-text)]'
    default:
      return 'border-[var(--color-border-subtle)] bg-[var(--color-bg-surface-elevated)] text-[var(--color-text-primary)]'
  }
}

export function PrintableDocumentShell({
  title,
  subtitle,
  productLabel,
  tenantLabel,
  sourceDisplayRef,
  documentStatus = 'working_copy',
  generatedAt,
  generatedBy,
  watermarkLabel,
  footer,
  signatureSection,
  appendixSection,
  children,
}: {
  title: string
  subtitle?: string
  productLabel?: string
  tenantLabel?: string
  sourceDisplayRef?: string
  documentStatus?: PrintDocumentStatus
  generatedAt?: string
  generatedBy?: string
  watermarkLabel?: string | false
  footer?: ReactNode
  signatureSection?: ReactNode
  appendixSection?: ReactNode
  children: ReactNode
}) {
  const resolvedGeneratedAt = generatedAt ?? new Date().toISOString()
  const statusLabel = formatDocumentStatus(documentStatus)
  const metadataItems = [
    productLabel ? { label: 'Product', value: productLabel } : null,
    tenantLabel ? { label: 'Tenant', value: tenantLabel } : null,
    sourceDisplayRef ? { label: 'Source reference', value: sourceDisplayRef } : null,
    { label: 'Generated', value: formatDateTime(resolvedGeneratedAt) },
    generatedBy ? { label: 'Generated by', value: generatedBy } : null,
  ].filter((item): item is { label: string; value: string } => item !== null)

  return (
    <section
      className="stl-print-document relative mx-auto max-w-5xl bg-[var(--color-bg-surface)] px-6 py-8 text-[var(--color-text-primary)] shadow-sm"
      data-print-document
      data-print-surface
    >
      {watermarkLabel ? <DraftWatermark label={watermarkLabel} /> : null}
      <div className="relative space-y-6">
        <header className="border-b border-[var(--color-border-subtle)] pb-5" data-print-section="document-header">
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div className="min-w-0">
              {productLabel || tenantLabel ? (
                <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[var(--color-text-muted)]">
                  {[productLabel, tenantLabel].filter(Boolean).join(' · ')}
                </p>
              ) : null}
              <h1 className="mt-2 break-words text-3xl font-semibold text-[var(--color-text-primary)]">{title}</h1>
              {subtitle ? <p className="mt-2 max-w-4xl text-sm leading-6 text-[var(--color-text-secondary)]">{subtitle}</p> : null}
            </div>
            <div className="shrink-0 text-right">
              <span
                className={`inline-flex items-center rounded-full border px-3 py-1 text-xs font-semibold uppercase tracking-wide ${documentStatusClasses(documentStatus)}`}
              >
                {statusLabel}
              </span>
              {sourceDisplayRef ? (
                <p className="mt-3 text-xs font-medium uppercase tracking-wide text-[var(--color-text-muted)]">
                  Source reference
                  <br />
                  <span className="text-sm font-semibold normal-case tracking-normal text-[var(--color-text-primary)]">
                    {sourceDisplayRef}
                  </span>
                </p>
              ) : null}
            </div>
          </div>

          {metadataItems.length > 0 ? (
            <dl
              className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4"
              data-print-section="document-metadata"
            >
              {metadataItems.map((item) => (
                <div
                  key={item.label}
                  className="rounded-lg border border-[var(--color-border-subtle)] bg-[var(--color-bg-surface-elevated)] p-3"
                >
                  <dt className="text-[11px] font-semibold uppercase tracking-wide text-[var(--color-text-muted)]">
                    {item.label}
                  </dt>
                  <dd className="mt-2 break-words text-sm font-medium text-[var(--color-text-primary)]">{item.value}</dd>
                </div>
              ))}
            </dl>
          ) : null}
        </header>

        <div className="space-y-6" data-print-section="document-body">
          {children}
        </div>

        {signatureSection ? (
          <section
            className="break-before-page space-y-3 border-t border-[var(--color-border-subtle)] pt-5"
            data-print-section="signature-section"
            data-print-break-before="page"
          >
            <h2 className="text-sm font-semibold uppercase tracking-wide text-[var(--color-text-muted)]">
              Signature / approval
            </h2>
            <div className="rounded-lg border border-[var(--color-border-subtle)] bg-[var(--color-bg-surface)] p-4">
              {signatureSection}
            </div>
          </section>
        ) : null}

        {appendixSection ? (
          <section
            className="break-before-page space-y-3 border-t border-[var(--color-border-subtle)] pt-5"
            data-print-section="appendix-section"
            data-print-break-before="page"
          >
            <h2 className="text-sm font-semibold uppercase tracking-wide text-[var(--color-text-muted)]">
              Appendix / attachments
            </h2>
            <div className="rounded-lg border border-[var(--color-border-subtle)] bg-[var(--color-bg-surface)] p-4">
              {appendixSection}
            </div>
          </section>
        ) : null}

        {footer ? (
          <footer
            className="border-t border-[var(--color-border-subtle)] pt-4 text-sm text-[var(--color-text-secondary)]"
            data-print-section="document-footer"
          >
            {footer}
          </footer>
        ) : null}
      </div>
    </section>
  )
}

export function PrintablePageShell({
  title,
  subtitle,
  footer,
  children,
}: {
  title: string
  subtitle?: string
  footer?: ReactNode
  children: ReactNode
  }) {
  return (
    <section className="stl-print-page mx-auto max-w-5xl rounded-xl border border-[var(--color-border-subtle)] bg-[var(--color-bg-surface)] p-6 text-[var(--color-text-primary)] shadow-sm">
      <header className="border-b border-[var(--color-border-subtle)] pb-4">
        <h1 className="text-2xl font-semibold text-[var(--color-text-primary)]">{title}</h1>
        {subtitle ? <p className="mt-2 text-sm text-[var(--color-text-secondary)]">{subtitle}</p> : null}
      </header>
      <div className="mt-6 space-y-6">{children}</div>
      {footer ? (
        <footer className="mt-8 border-t border-[var(--color-border-subtle)] pt-4 text-sm text-[var(--color-text-muted)]">{footer}</footer>
      ) : null}
    </section>
  )
}

export function PrintableDocumentHeader({
  title,
  metadata,
}: {
  title: string
  metadata?: ReactNode
  }) {
  return (
    <header className="mb-6 border-b border-[var(--color-border-subtle)] pb-4">
      <h2 className="text-xl font-semibold text-[var(--color-text-primary)]">{title}</h2>
      {metadata ? <div className="mt-2 text-sm text-[var(--color-text-secondary)]">{metadata}</div> : null}
    </header>
  )
}

export function PrintableDocumentFooter({ children }: { children: ReactNode }) {
  return <footer className="mt-8 border-t border-[var(--color-border-subtle)] pt-4 text-sm text-[var(--color-text-muted)]">{children}</footer>
}

export function DraftWatermark({ label = 'Draft' }: { label?: string }) {
  return (
    <div
      aria-hidden
      className="pointer-events-none absolute inset-0 flex items-center justify-center overflow-hidden"
    >
      <span className="rotate-[-24deg] text-6xl font-bold uppercase tracking-[0.25em] text-[var(--color-text-muted)]/70">
        {label}
      </span>
    </div>
  )
}

function badgeClasses() {
  return 'inline-flex items-center rounded-full border border-[var(--color-border-subtle)] bg-[var(--color-bg-surface-elevated)] px-3 py-1 text-xs font-semibold uppercase tracking-wide text-[var(--color-text-secondary)]'
}

export function OfficialCopyBadge() {
  return <span className={badgeClasses()}>Official copy</span>
}

export function RedactedCopyBadge() {
  return <span className={badgeClasses()}>Redacted copy</span>
}

export function LabelPreview({
  title,
  children,
}: {
  title: string
  children: ReactNode
}) {
  return (
    <section className="inline-flex min-h-40 min-w-64 flex-col rounded-lg border border-[var(--color-border-default)] bg-[var(--color-bg-surface)] p-4 text-[var(--color-text-primary)] shadow-sm">
      <p className="text-xs font-semibold uppercase tracking-wide text-[var(--color-text-muted)]">{title}</p>
      <div className="mt-3 flex-1">{children}</div>
    </section>
  )
}

export function PacketPreview({
  title,
  sections,
}: {
  title: string
  sections: Array<{ title: string; content: ReactNode }>
}) {
  return (
    <section className="rounded-xl border border-[var(--color-border-subtle)] bg-[var(--color-bg-surface)] p-6 text-[var(--color-text-primary)] shadow-sm">
      <h2 className="text-xl font-semibold text-[var(--color-text-primary)]">{title}</h2>
      <div className="mt-4 space-y-4">
        {sections.map((section) => (
          <article
            key={section.title}
            className="rounded-lg border border-[var(--color-border-subtle)] bg-[var(--color-bg-surface-elevated)] p-4"
          >
            <h3 className="text-sm font-semibold uppercase tracking-wide text-[var(--color-text-muted)]">
              {section.title}
            </h3>
            <div className="mt-3">{section.content}</div>
          </article>
        ))}
      </div>
    </section>
  )
}

type ActionButtonProps = {
  label: string
  busyLabel?: string
  isPending?: boolean
  disabled?: boolean
  onClick?: () => void
}

function ActionButton({
  label,
  busyLabel,
  isPending = false,
  disabled = false,
  onClick,
}: ActionButtonProps) {
  return (
    <button
      type="button"
      className="inline-flex items-center rounded-lg border border-[var(--color-border-default)] bg-[var(--color-bg-control)] px-3 py-2 text-sm font-medium text-[var(--color-text-primary)] shadow-sm transition hover:bg-[var(--color-bg-control-hover)] disabled:cursor-not-allowed disabled:opacity-50"
      onClick={onClick}
      disabled={disabled || isPending}
    >
      {isPending ? busyLabel ?? label : label}
    </button>
  )
}

export function DownloadPdfButton(props: Omit<ActionButtonProps, 'busyLabel'>) {
  return <ActionButton {...props} busyLabel="Preparing PDF…" />
}

export function ArchiveOfficialCopyButton(props: Omit<ActionButtonProps, 'busyLabel'>) {
  return <ActionButton {...props} busyLabel="Archiving…" />
}

export function ReprintReasonDialog({
  open,
  title = 'Reason required',
  confirmLabel = 'Continue',
  onClose,
  onConfirm,
}: {
  open: boolean
  title?: string
  confirmLabel?: string
  onClose: () => void
  onConfirm: (reason: string) => void
}) {
  const reasonId = useId()
  const [reason, setReason] = useState('')

  if (!open) {
    return null
  }

  return (
    <div
      className="rounded-xl border border-[var(--color-border-default)] bg-[var(--color-bg-surface)] p-4 text-[var(--color-text-primary)] shadow-lg"
      data-print-hide
    >
      <h3 className="text-base font-semibold text-[var(--color-text-primary)]">{title}</h3>
      <label htmlFor={reasonId} className="mt-3 block text-sm text-[var(--color-text-secondary)]">
        Reprint reason
      </label>
      <textarea
        id={reasonId}
        value={reason}
        onChange={(event) => setReason(event.target.value)}
        rows={4}
        className="mt-2 w-full rounded-lg border border-[var(--color-border-default)] bg-[var(--color-bg-control)] px-3 py-2 text-sm text-[var(--color-text-primary)]"
      />
      <div className="mt-4 flex flex-wrap gap-2">
        <button
          type="button"
          className="rounded-lg border border-[var(--color-border-default)] bg-[var(--color-bg-control)] px-3 py-2 text-sm font-medium text-[var(--color-text-primary)]"
          onClick={onClose}
        >
          Cancel
        </button>
        <button
          type="button"
          className="rounded-lg border border-[var(--color-accent)] bg-[var(--color-accent)] px-3 py-2 text-sm font-medium text-[var(--color-on-accent)] disabled:opacity-50"
          disabled={!reason.trim()}
          onClick={() => {
            onConfirm(reason.trim())
            setReason('')
          }}
        >
          {confirmLabel}
        </button>
      </div>
    </div>
  )
}

export function PrintPreviewRoute({
  title,
  subtitle,
  productLabel,
  tenantLabel,
  sourceDisplayRef,
  documentStatus = 'working_copy',
  generatedAt,
  generatedBy,
  watermarkLabel,
  footer,
  signatureSection,
  appendixSection,
  actions,
  children,
}: {
  title: string
  subtitle?: string
  productLabel?: string
  tenantLabel?: string
  sourceDisplayRef?: string
  documentStatus?: PrintDocumentStatus
  generatedAt?: string
  generatedBy?: string
  watermarkLabel?: string | false
  footer?: ReactNode
  signatureSection?: ReactNode
  appendixSection?: ReactNode
  actions?: ReactNode
  children: ReactNode
}) {
  return (
    <div className="space-y-4" data-print-preview="true">
      {actions ? <div className="flex flex-wrap gap-2" data-print-hide>{actions}</div> : null}
      <PrintableDocumentShell
        title={title}
        subtitle={subtitle}
        productLabel={productLabel}
        tenantLabel={tenantLabel}
        sourceDisplayRef={sourceDisplayRef}
        documentStatus={documentStatus}
        generatedAt={generatedAt}
        generatedBy={generatedBy}
        watermarkLabel={watermarkLabel}
        footer={footer}
        signatureSection={signatureSection}
        appendixSection={appendixSection}
      >
        {children}
      </PrintableDocumentShell>
    </div>
  )
}
