namespace RoutArr.Api.Contracts;

public sealed record DispatchPlanSummaryResponse(
    Guid DispatchPlanId,
    string DispatchNumber,
    string Title,
    string Description,
    DateTimeOffset DispatchDate,
    string DispatchType,
    string Status,
    string? PlannerPersonId,
    string? DispatcherPersonId,
    Guid? StaffarrSiteId,
    IReadOnlyList<string> RouteRefs,
    IReadOnlyList<string> TripRefs,
    IReadOnlyList<string> BlockerRefs,
    string Notes,
    string CreatedByPersonId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ReleasedAt,
    string? ReleasedByPersonId,
    DateTimeOffset? CompletedAt,
    DateTimeOffset? CanceledAt,
    string? CancelReason);

public sealed record DispatchPlanDetailResponse(
    Guid DispatchPlanId,
    string DispatchNumber,
    string Title,
    string Description,
    DateTimeOffset DispatchDate,
    string DispatchType,
    string Status,
    string? PlannerPersonId,
    string? DispatcherPersonId,
    Guid? StaffarrSiteId,
    IReadOnlyList<string> RouteRefs,
    IReadOnlyList<string> TripRefs,
    IReadOnlyList<string> BlockerRefs,
    string Notes,
    string CreatedByPersonId,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? ReleasedAt,
    string? ReleasedByPersonId,
    DateTimeOffset? CompletedAt,
    DateTimeOffset? CanceledAt,
    string? CancelReason);

public sealed record CreateDispatchPlanRequest(
    string Title,
    string Description,
    DateTimeOffset DispatchDate,
    string DispatchType,
    string? PlannerPersonId,
    string? DispatcherPersonId,
    Guid? StaffarrSiteId,
    IReadOnlyList<string>? RouteRefs,
    IReadOnlyList<string>? TripRefs,
    IReadOnlyList<string>? BlockerRefs,
    string? Notes);
